import type { Question } from './types';

export const GRADER_QUESTIONS: Question[] = [
  // ─── INFORMATION ─────────────────────────────────────────────────────────
  {
    id: 'q_ops_handbook',
    shortLabel: "Manufacturer's operation handbook available",
    text: "Is the manufacturer's operation handbook available for this item of plant? (You cannot answer N/A)",
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Operation Handbook',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        "The manufacturer's operation handbook has been supplied for this item of plant. This handbook must be available at all times to all potential operators and supervisory staff. All potential operators must read and be familiar with this handbook prior to operating. A complete risk assessment/Job Safety Analysis must be undertaken covering all operating processes and environments associated with this item of plant. SWMS should be produced for specific tasks associated with use of this item of plant.",
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_maint_manual',
    shortLabel: "Manufacturer's maintenance manual(s) available",
    text: "Is the manufacturer's maintenance manual(s) available for this item of plant? (You cannot answer N/A)",
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Maintenance Manual',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        "The manufacturer's maintenance manual(s) has been supplied for this item of plant. These manual(s) must be available at all times to all users and maintenance staff of this item of plant. All users and maintenance staff must read and be familiar with these handbook(s) prior to maintaining or repairing this item of plant. A complete risk assessment/JSEA must be undertaken covering all inspection, maintenance, servicing and transportation requirements of this piece of plant prior to use.",
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_service_records',
    shortLabel: 'Service and maintenance records available',
    text: 'Are the service and maintenance records available for this item of plant? (You cannot answer N/A)',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Service Records',
      hazards: ['OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Service and maintenance records are available for this item of plant. These records must continue to be managed and available at all times as part of your service and maintenance programme. (This programme includes the undertaking of regular inspections of the item of plant with specific reference to all OEM prescribed, scheduled and non scheduled service and maintenance requirements).',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_preop_checklist',
    shortLabel: 'Pre-operational safety checklist available',
    text: 'Is a pre-operational safety checklist available for this Grader? (You cannot answer N/A)',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Pre-op Checklist Grader',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'A pre-operational checklist is available for this Grader. All operators must complete this checklist prior to operating this Grader.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_sop',
    shortLabel: 'Safe Operation Procedures available',
    text: 'Are Safe Operation Procedures available for this Grader? (You cannot answer N/A)',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'SOP Grader',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'Safe Operation Procedures are available for this Grader. The information in the Safe Operation Procedures must be followed at all times whilst operating this Grader.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_operator_qualified',
    shortLabel: 'Operators qualified, trained, and experienced',
    text: 'Are all persons who operate this item of plant qualified, trained and experienced to do so, and where necessary do they hold the relevant certification/license?',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Operator Competency',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'CRITICAL', value: 24 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'Only persons who are qualified, trained and experienced and/or hold the relevant certification/license can operate this item of plant. If there is not a competent/licensed person available for operation of this item of plant then only persons who are supervised by a competent/licensed person can operate this item of plant.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_swms_loading',
    shortLabel: 'SWMS/SOP for loading and unloading available',
    text: 'Are specific guidelines/SWMS/SOP available for loading and unloading this item of plant to & from the load deck of a truck or trailer?',
    surveyGroup: 'Information',
    allowNA: true,
    treatment: {
      name: 'SWMS Loading/Unloading',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DELIVERY',
      treatmentText:
        'Ensure that all operators follow approved SWMS/SOP when loading and unloading this machine to and from a flat top truck or trailer, low loader or tilt tray.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_swms_restraint',
    shortLabel: 'SWMS/SOP for load restraint available',
    text: 'Are specific load restraint guidelines/SWMS/SOP available when restraining this item of plant on to the load deck of a truck or trailer?',
    surveyGroup: 'Information',
    allowNA: true,
    treatment: {
      name: 'SWMS Load Restraint',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DELIVERY',
      treatmentText:
        'Ensure that all operators follow the approved SWMS/SOP when restraining this machine for transport.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },

  // ─── BRAKES ──────────────────────────────────────────────────────────────
  {
    id: 'q_brakes_functional',
    shortLabel: 'Brakes fully functional',
    text: 'Are the brakes fitted to this item of plant fully functional?',
    surveyGroup: 'Brakes',
    allowNA: false,
    treatment: {
      name: 'Brakes',
      hazards: ['CRUSHING', 'COLLISION'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The brakes fitted to this item of plant must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation. The brakes must be regularly inspected and tested. These inspections and tests must be documented as part of your plant safety programme.',
      references: 'AS3450',
    },
  },
  {
    id: 'q_park_brake',
    shortLabel: 'Park (hand) brake fitted and fully functional',
    text: 'Is this item of plant fitted with a fully functional park (hand) brake, which meets the following requirements – 1. Is separate to the service brakes 2. Has a device which maintains the brake in the on position until intentionally disengaged?',
    surveyGroup: 'Brakes',
    allowNA: false,
    treatment: {
      name: 'Park Brake',
      hazards: ['CRUSHING', 'COLLISION'],
      prelimRating: { label: 'CRITICAL', value: 24 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional park (hand) brake which meets the following requirements – 1. Is separate to the service brakes 2. Has a device which maintains the brake in the on position until intentionally disengaged. The park brake must be regularly inspected and tested. These inspections and tests must be documented as part of your plant safety programme.',
      references: 'AS3450',
    },
  },

  // ─── CABIN / WORK AREA ───────────────────────────────────────────────────
  {
    id: 'q_cabin_access_steps',
    shortLabel: 'Cabin access/egress — slip-resistant steps, 3 points of contact',
    text: 'Does the cabin/work area access and egress have slip resistant steps that are free from damage, located at the appropriate height to allow safe access and egress without undue bodystressing/strains, with three points of contact available at all times?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Operator Work Area Access/Egress',
      hazards: ['SLIPPING'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'Safe access and egress to the cabin/work area(s) must be maintained at all times whilst this item of plant is in operation. It must be non slip, free from damage, located at a height so as to not cause undue body stresses and strains with three points of contact available to personnel at all times. All personnel must – 1. Always face the item of plant during access and egress. 2. Always maintain three points of contact during access and egress. 3. Never carry an object(s) in his/her hand(s) during access and egress. 4. Never jump off machine.',
      references: 'AS5327',
    },
  },
  {
    id: 'q_cabin_access_label',
    shortLabel: 'Cabin access — instruction label present (face machine, 3 points of contact)',
    text: 'Does the cabin/work area access and egress have an instruction label adjacent to advise all personnel of the following - 1. Always face the item of plant during access and egress. 2. Always maintain three points of contact during access and egress. 3. Ensure steps are clean. 4. Never jump off machine?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Access/Egress Instruction Label',
      hazards: ['FALLING', 'SLIPPING'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'An instruction label is fitted adjacent access/egress areas to advise all personnel of the following – 1. Always face the item of plant during access and egress. 2. Always maintain three points of contact during access and egress. 3. Ensure the steps are clean. 4. Never jump off machine. This label must be clear and legible at all times whilst this item of plant is in operation.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_two_exits',
    shortLabel: 'Operator cabin has minimum 2 possible exits',
    text: 'Does the operator cabin/work area have a minimum of two (2) possible exits? (answer N/A if this machine has no cab)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if this machine has no cab',
    treatment: {
      name: 'Two Operator Exits',
      hazards: ['ENTRAPMENT'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The operator cabin/work area on this item of plant has a minimum of two (2) possible exits. These must be functional and accessible at all times whenever the item of plant is manned, whether during operation or maintenance activities.',
      references: 'AS5327',
    },
  },
  {
    id: 'q_emergency_exits_compliance',
    shortLabel: 'Emergency exits — labelled, instructions clear, tools available',
    text: 'Do the emergency exits for this item of plant meet the following requirements - 1. Clearly and legibly labelled 2. Instructions for use are clear and legible and located adjacent the exit 3. Any required tools required for use are available e.g. Emergency hammers? (Answer NA if no emergency exits due to no cabin)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if no emergency exits due to no cabin',
    treatment: {
      name: 'Emergency Exits',
      hazards: ['ENTRAPMENT'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The emergency exits for this item of plant meet the following requirements – 1. Clearly and legibly labelled 2. Instructions for use are clear and legible and located adjacent the exit 3. Any required tools required for use are available e.g. Emergency hammers. These exits must be legibly labelled and kept serviceable and verified by the operator/owner at all times whenever the item of plant is manned, whether during operation or maintenance activities.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_windows_screens',
    shortLabel: 'Cabin windows — present, clean, safety glass, no cracks',
    text: 'Are all cabin/work area windows and screens present, clean, constructed from safety glass and free from cracks and other damage? (N.B. Perspex is not acceptable)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if no cabin',
    treatment: {
      name: 'Windows & Screens',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Ensure the cabin/work area safety glass windows and screens are kept clean and free from cracks and other damage at all times whilst this item of plant is in use.',
      references: 'AS/NZS4024.1201, ISO20474-',
    },
  },
  {
    id: 'q_windscreen_wipers',
    shortLabel: 'Windscreen wipers and washers fully functional',
    text: 'Is this item of plant fitted with fully functional windscreen wipers and washers? (if this item of plant does not have a screen then answer n/a)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: "Answer N/A if this item of plant does not have a screen",
    treatment: {
      name: 'Windscreen Wipers',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The windscreen wipers and washers fitted to this item of plant must be kept serviceable and verified by the operator/owner at all times.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'q_loose_items',
    shortLabel: 'All items that could cause harm securely restrained',
    text: 'Are all items that could cause harm to the operator in the event of a collision or rollover securely restrained?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Loose Items - Operator Work Area',
      hazards: ['CRUSHING', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All items that could cause harm to the operator in the event of a collision or rollover are securely restrained.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_work_area_floors',
    shortLabel: 'Work area floors non-slip and free from debris',
    text: 'Are all work area floors non-slip and free from damage and debris (including rubbish, tools, etc)?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Work Area Floors',
      hazards: ['INCORRECT OPERATION', 'SLIPPING'],
      prelimRating: { label: 'MEDIUM', value: 9 },
      residualRating: { label: 'LOW', value: 4 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All work area floors are non-slip and free from damage & debris. Floor area must remain non-slip and free from damage & debris, including rubbish, tools and other items, at all times whilst this item of plant is in use.',
      references: 'AS/NZS4024.1201, ISO20474-',
    },
  },
  {
    id: 'q_operator_mirrors',
    shortLabel: 'At least 2 functional rear view mirrors (one each side)',
    text: 'Does this item of plant have at least two (2) functional operator rear view mirrors, one on each side of the item of plant?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Operator Mirrors',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The operator rear view mirrors fitted to this item of plant must be kept serviceable and verified by the operator/owner and kept clean at all times. There must always be at least one mirror on each side to provide rear vision to the operator to avoid striking bystanders and objects.',
      references: 'AS/NZS4024.1201, ISO14401.1',
    },
  },
  {
    id: 'q_operator_seat',
    shortLabel: 'Ergonomic seat — free from damage, permanently fitted',
    text: 'Is there an ergonomic seat which is free from damage and tears, permanently and securely fitted to the operator work area of this item of plant?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Operator Seat',
      hazards: ['NON COMPLIANCE', 'STRAINS'],
      prelimRating: { label: 'MEDIUM', value: 9 },
      residualRating: { label: 'LOW', value: 1 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The operator seat fitted to this item of plant must remain free from damage and tears, and be permanently and securely fitted at all times.',
      references: 'AS/NZS4024.1401 , ISO20474-',
    },
  },
  {
    id: 'q_seat_belt',
    shortLabel: 'Operator seat belt — free from damage, permanently attached',
    text: 'Is this item of plant fitted with an operator seat belt which is free from damage and sturdily and permanently attached?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Seat Belt',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with an operator seat belt. This seat belt must be free from damage, and permanently and sturdily attached at all times whilst this item of plant is in operation. Operators must use this seat belt at all times during operation.',
      references: 'ISO6683',
    },
  },
  {
    id: 'q_no_passenger_label',
    shortLabel: '"Operator only, No passengers" hazard warning label',
    text: 'If this item of plant does not have a passenger seat, is there a clear and legible hazard warning label fitted re: Operator only, No passengers? (answer n/a if this item of plant has a passenger seat)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant has a passenger seat',
    treatment: {
      name: 'Passenger Seat Label',
      hazards: ['CRUSHING', 'FALLING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with a clear hazard warning label re: Operator only, No passengers. Passengers must not be carried at anytime. This label must be clear and legible at all times whilst this item of plant is in operation.',
      references: 'AS1319- , State Health & Safety Legislation & Regulation',
    },
  },
  {
    id: 'q_air_conditioning',
    shortLabel: 'Working air conditioner in fully enclosed cabin',
    text: 'Is this item of plant fitted with a fully enclosed cabin, if so is there a working air conditioner fitted? (answer n/a if open or no cabin)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if open or no cabin',
    treatment: {
      name: 'Air Conditioning',
      hazards: ['HEAT STROKE', 'DEHYDRATION'],
      prelimRating: { label: 'MEDIUM', value: 9 },
      residualRating: { label: 'LOW', value: 4 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with an air conditioned cabin. This air conditioned cabin helps control the air quality and temperature for the operator and also provides shade from the sun. The air conditioner must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_open_cabin',
    shortLabel: 'Open or no cabin — appropriate controls available',
    text: 'Is this item of plant fitted with either an open operator cabin (not fully enclosed) or with no operator cabin? (Answer n/a if a fully enclosed cabin)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if a fully enclosed cabin',
    treatment: {
      name: 'Open Cabin',
      hazards: ['BURNS'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'MEDIUM', value: 12 },
      operationCategory: 'OPERATION',
      treatmentText:
        'Dust, exhaust fumes, chemical fumes, sunstroke and sunburn pose serious risk to the operator both short and long term. The appropriate controls for all of these hazards must always be available whilst this item of plant is in operation. If these controls e.g. hats, sunscreen, dust masks etc are not available then operation of this item of plant must cease until these are made available to all operators.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_mobile_phone_label',
    shortLabel: '"Mobile phones must not be used whilst operating" instruction label',
    text: 'Is this item of plant fitted with an instruction label in clear view of the operator which advises that - "Mobile phones must not be used whilst operating machine"?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Phone Use Label',
      hazards: ['COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with an instruction label advising that mobile phones must not be used whilst operating this machine. Accordingly all operators must not use a mobile phone at any time whilst operating machine. If phone use is necessary then operator must place machine in park configuration in a safe position prior to phone use. Operators MUST adhere to this advice at all times. This label must be clear and legible at all times whilst this item of plant is in operation.',
      references: 'AS1319- , ISO31000',
    },
  },
  {
    id: 'q_rear_camera',
    shortLabel: 'Rear camera suitable for day and night operations',
    text: 'Is this item of plant fitted with a rear camera suitable for day and night operations which is either constantly on or automatically activated when reverse gear is selected?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Rear Camera',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with a rear camera which is suitable for day and night operations. This camera and screen must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201, ISO31000',
    },
  },
  {
    id: 'q_work_platforms_guardrail',
    shortLabel: 'Operator work platforms have approved guardrails (≥0.5m)',
    text: 'Do all operator work platforms above 0.5m have an approved guardrail that meets the following requirements: 1. At least 1.1m high 2. Has a mid rail 3. All sides and ends have a kick plate at least 100mm high? (answer n/a if no platforms where feet are above 0.5m)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if there are no platforms where the operator feet are above 0.5m',
    treatment: {
      name: 'Handrails',
      hazards: ['FALLING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All operator work platforms are reported/observed as fitted with guardrails which meet the following requirements: 1. All guardrails are at least 1.1m high 2. All guardrails have a mid rail 3. All sides and ends have a kick plate which is at least 100mm high. These work platforms and/or access points must have guardrails present that are kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS5327',
    },
  },

  // ─── CONTROLS ────────────────────────────────────────────────────────────
  {
    id: 'q_restricted_access',
    shortLabel: 'Restricted operator access (key operated switch)',
    text: 'Is this item of plant fitted with restricted operator access e.g. a key operated On/Off switch?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Restricted Access Switches',
      hazards: ['INCORRECT OPERATION', 'OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'MEDIUM', value: 13 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a device to restrict operators. A code/key must only be given to those that have appropriate experience or training.',
      references: 'AS20474.1',
    },
  },
  {
    id: 'q_warning_device_horn',
    shortLabel: 'Fully functional warning device (horn) fitted',
    text: 'Is this item of plant fitted with a fully functional warning device, such as a horn, which is clearly and easily identified?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Warning Device (Horn)',
      hazards: ['CRUSHING', 'COLLISION'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional audible warning device such as a horn. This must be easily accessed by the operator, and easily identifiable by nearby pedestrians. All operators should ensure the warning devices are functional at the start of each shift, by completing pre-start checklists. Warning devices should operate automatically where appropriate (eg reversing).',
      references: 'ISO7731, ISO9533',
    },
  },
  {
    id: 'q_controls_ergonomic',
    shortLabel: 'All controls ergonomically placed',
    text: 'Are all controls including all levers, buttons, pedals, switches etc. ergonomically placed in relation to the operator work position?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Controls Ergonomics',
      hazards: ['STRAINS'],
      prelimRating: { label: 'HIGH', value: 19 },
      residualRating: { label: 'LOW', value: 5 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        "All controls including all levers, buttons, pedals, switches etc, are placed near the operator work position and are easy to reach and operate during the execution of the operator's normal duties. This applies for all persons within the 95th percentile of the normal population distribution.",
      references: 'AS/NZS4024.1901',
    },
  },
  {
    id: 'q_controls_labelled',
    shortLabel: 'All controls clearly labelled as to purpose and operation',
    text: 'Are all controls including all levers, buttons, pedals, switches etc. clearly labelled as to their purpose and method of operation?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Control Labels',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'All controls including all levers, buttons, pedals, switches etc. are clearly labelled as to their purpose and method of operation. These labels must be maintained in a clean and serviceable condition at all times.',
      references: 'AS/NZS4024.1905',
    },
  },
  {
    id: 'q_intuitive_controls',
    shortLabel: 'Controls orientated consistently with machine action',
    text: 'Are all controls orientated so that the movement of the control is consistent with the action of the machine e.g. moving a control lever to the left results in the machine turning to the left?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Intuitive Controls',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 20 },
      residualRating: { label: 'MEDIUM', value: 14 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The controls fitted to this item of plant are orientated so that the movement of the control is consistent with the action of the machine e.g. moving a control lever to the left results in the machine turning to the left. This design feature must be maintained at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1906',
    },
  },
  {
    id: 'q_controls_non_slip',
    shortLabel: 'All controls non-slip and free from damage',
    text: 'Are all controls including all levers, buttons, pedals, switches etc. non-slip and free from damage?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Control Levers/Pedals/Buttons',
      hazards: ['INCORRECT OPERATION', 'SLIPPING'],
      prelimRating: { label: 'HIGH', value: 17 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All controls including all levers, buttons, pedals, switches etc. must be kept non-slip and free from damage at all times.',
      references: 'AS/NZS4024.1901',
    },
  },
  {
    id: 'q_neutral_start',
    shortLabel: 'Working neutral start control fitted',
    text: 'Does this item of plant have a working neutral start control fitted? (you cannot answer N/A)',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Neutral Start',
      hazards: ['CRUSHING', 'ENTANGLEMENT', 'STRIKING', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant has neutral start control in place. It must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS4024.1603',
    },
  },
  {
    id: 'q_reverse_alarm',
    shortLabel: 'Reverse movement alarm — auto activated when reverse selected',
    text: 'Is this item of plant fitted with a reverse movement awareness alarm which is automatically activated when reverse gear is selected? (Answer NO if alarm is manually activated)',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Reverse Movement Alarm',
      hazards: ['CRUSHING', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a reverse movement awareness alarm which is automatically activated when reverse gear is selected. This alarm must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'ISO7731, ISO9533',
    },
  },
  {
    id: 'q_emergency_stop_internal',
    shortLabel: 'Emergency stop/shutdown — at normal operating position',
    text: 'Is this item of plant fitted with an emergency stop/shutdown device, capable of shutting the machine down, located at the normal operating position?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Emergency Stop/Shutdown Device',
      hazards: ['CRUSHING', 'ENTANGLEMENT', 'FIRE'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with an emergency stop/shutdown device, capable of shutting the machine down, located at the normal operating position. This device must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS20474.1',
    },
  },
  {
    id: 'q_emergency_stop_external',
    shortLabel: 'Emergency stop/shutdown — on external surface, easily accessible',
    text: 'Is this item of plant fitted with an emergency stop/shutdown device, capable of shutting the machine down located on at least one external surface of the machine and is easily accessible?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'External Emergency Stop/Shutdown Device',
      hazards: ['CRUSHING', 'ENTANGLEMENT', 'FIRE'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with an emergency stop/shutdown device, capable of shutting the machine down located on at least one external surface of the machine and is easily accessible. This device must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS20474.1',
    },
  },

  // ─── OPERATOR PROTECTIVE GUARDS ──────────────────────────────────────────
  {
    id: 'q_rops_fitted',
    shortLabel: 'ROPS fitted (AS 2294 / ISO 3471) — operating mass >700kg',
    text: 'If the operating mass of this item of plant is greater than 700kg, has a Roll Over Protective Structure (ROPS) to AS 2294, ISO 3471, ISO 12117.1 or 2 or SAE J1040 been fitted? (answer n/a if operating mass is less than 700kg)',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if operating mass is less than 700kg',
    treatment: {
      name: 'Earthmoving ROPS',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'A Roll Over Protective Structure (ROPS) to AS 2294, ISO 3471, ISO 12117.1 or 2 or SAE J1040 is fitted to this item of plant. A permanent label stating this standard must be attached to the structure at all times. It must also carry a warning label re: wearing of seat belts at all times whilst this item of plant is in operation, and accordingly seat belts must be worn at all times during operation.',
      references: 'AS2294, ISO3471',
    },
  },
  {
    id: 'q_rops_free_damage',
    shortLabel: 'ROPS free from damage (no cuts, drill holes, welds, dents)',
    text: 'If this item of plant is fitted with a Roll Over Protective Structure (ROPS), is it free from damage, including cuts, drill holes, welds and dents? (answer n/a if no ROPS fitted)',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if no ROPS fitted',
    treatment: {
      name: 'ROPS Damage',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The Roll Over Protective Structure (ROPS) fitted to this item of plant must remain free from damage at all times whilst this item of plant is in operation.',
      references: 'AS2294, ISO3471',
    },
  },
  {
    id: 'q_rops_no_drill_label',
    shortLabel: 'ROPS — warning label: must not be cut, drilled, or welded',
    text: 'If this item of plant is fitted with a ROPS, is there a warning label present which states that it must not be damaged by cutting, drilling or welding? (answer n/a if no ROPS fitted)',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if no ROPS fitted',
    treatment: {
      name: 'ROPS Label',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The warning label stating that the ROPS must not be damaged at any time (including cuts, drill holes and welds) must be present, clean and legible at all times.',
      references: 'ISO3471',
    },
  },
  {
    id: 'q_rops_seatbelt_label',
    shortLabel: 'ROPS — label: "seatbelts must be worn"',
    text: 'If this item of plant is fitted with a ROPS, is there a clear and legible label present which states that "seatbelts must be worn"? (answer n/a if no ROPS fitted)',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if no ROPS fitted',
    treatment: {
      name: 'ROPS Seat Belt Label',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with a ROPS and has an advisory label stating that "seatbelts must be worn". This label must be present, clean and legible at all times. All operators and passengers must wear seatbelts whilst on this item of plant.',
      references: 'AS2294, ISO3471',
    },
  },
  {
    id: 'q_fops_level1',
    shortLabel: 'FOPS Level I fitted (ISO 3449 Level I)',
    text: 'Is this item of plant fitted with a Falling Objects Protective Structure (FOPS) to ISO 3449 Level I or ISO 10262 Level I? (Answer YES if compliance plate states ISO 3449 or ISO 10262 but not a level. Answer NO if no FOPS fitted. Answer N/A if Level II FOPS.)',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if Level II FOPS is fitted',
    treatment: {
      name: 'FOPS General',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'LOW', value: 5 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a Level I Falling Objects Protective Structure (FOPS). This structure is designed to protect the operator from small falling objects (e.g. bricks, small concrete blocks, hand tools). Before operating this item of plant a task based risk assessment must be conducted to determine the level of FOPS required. Level I - withstands 1,365 joules. Level II - withstands 11,600 joules. This task risk assessment must be undertaken before each operation, in particular when the item of plant is moved to a new location.',
      references: 'AS2294, ISO3449, ISO10262',
    },
  },
  {
    id: 'q_fops_level2',
    shortLabel: 'FOPS Level II fitted (ISO 3449 Level II)',
    text: 'Is this item of plant fitted with a Falling Objects Protective Structure (FOPS) to ISO 3449 Level II or ISO 10262 Level II? (Answer N/A if no FOPS or Level I FOPS.)',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if no FOPS or Level I FOPS is fitted',
    treatment: {
      name: 'FOPS Level II',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'LOW', value: 5 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a level II Falling Objects Protective Structure (FOPS). This structure is designed to protect the operator from heavy falling objects (e.g. trees, rocks). Care should still be exercised when operating in an area with a risk of falling objects.',
      references: 'AS2294, ISO3449',
    },
  },

  // ─── PPE ─────────────────────────────────────────────────────────────────
  {
    id: 'q_hearing_protection_operator',
    shortLabel: 'Hearing protection label — adjacent operator work area (≥85dB)',
    text: 'Does this item of plant have a hazard warning label attached adjacent the operator work area re: wearing of hearing protection? [Answer N/A if the SPL is less than 85 dB(A) at the operator work area]',
    surveyGroup: 'PPE',
    allowNA: true,
    naCondition: 'Answer N/A if the sound pressure level is less than 85 dB(A) at the operator work area',
    treatment: {
      name: 'Hearing Protection Label - Operator',
      hazards: ['HEARING LOSS'],
      prelimRating: { label: 'HIGH', value: 19 },
      residualRating: { label: 'MEDIUM', value: 14 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The hazard warning label(s) re: wearing of hearing protection attached to this item of plant refer to the level of noise produced. Permanent hearing damage will result if hearing protection is not worn. These labels must be present, clear and legible at all times whilst this item of plant is in operation.',
      references: 'AS3781- , AS/NZS1269',
    },
  },
  {
    id: 'q_hearing_protection_bystanders',
    shortLabel: 'Hearing protection label — visible to bystanders at 10m (≥85dB)',
    text: 'Does this item of plant have hazard warning labels attached which are visible to bystanders from a distance of 10m re: wearing of hearing protection? [Answer N/A if the SPL is less than 85 dB(A) at a distance of 6m]',
    surveyGroup: 'PPE',
    allowNA: true,
    naCondition: 'Answer N/A if the sound pressure level is less than 85 dB(A) at a distance of 6m',
    treatment: {
      name: 'Hearing Protection Label - Bystanders',
      hazards: ['HEARING LOSS'],
      prelimRating: { label: 'HIGH', value: 19 },
      residualRating: { label: 'MEDIUM', value: 14 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The hazard warning labels re: wearing of hearing protection for bystanders attached to this item of plant refer to the level of noise produced. Permanent hearing damage will result if hearing protection is not worn. These labels must be present, clear and legible at all times whilst this item of plant is in operation.',
      references: 'AS3781- , AS/NZS1269',
    },
  },

  // ─── LIGHTING ────────────────────────────────────────────────────────────
  {
    id: 'q_head_work_lights',
    shortLabel: 'Serviceable headlights, reversing lights, front/rear and operator lighting',
    text: 'Does this item of plant have serviceable head lights, reversing lights, front and rear lighting to the work area, lighting to the operator controls and work areas?',
    surveyGroup: 'Lighting',
    allowNA: false,
    treatment: {
      name: 'Machine Lights',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with self contained lighting. All of these lights must be kept serviceable and verified by the operator/owner whilst this item of plant is in operation in areas of reduced light. If any of these lights stop working the operation must cease immediately and the faulty light be repaired before operation can continue in the areas of reduced light.',
      references: 'ISO20474-',
    },
  },
  {
    id: 'q_presence_turn_brake_lights',
    shortLabel: 'Fully functional side/rear presence, turning, and braking lights',
    text: 'Does this item of plant have fully functional side and rear lighting which indicate presence, turning and braking?',
    surveyGroup: 'Lighting',
    allowNA: false,
    treatment: {
      name: 'Turning, Braking & Presence Lights',
      hazards: ['COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with lighting to indicate presence, turning and braking. All of these lights must be kept serviceable and verified by the operator/owner whilst this item of plant is in operation in areas of reduced light. If any of these lights stop working the operation must cease immediately and the faulty light be repaired before operation can continue.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'q_beacon',
    shortLabel: '55W amber rotating/strobe safety beacon — visible 200m in all directions',
    text: 'Is this item of plant fitted with a fully functional 55 watt amber rotating or strobe safety beacon which is visible up to 200m in all directions and fitted in the most appropriate location?',
    surveyGroup: 'Lighting',
    allowNA: false,
    treatment: {
      name: 'Beacon',
      hazards: ['COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a safety beacon. This beacon must meet the following criteria at all times whilst this item of plant is in operation – Is visible up to 200m in all directions (allowing for intermittent obstruction from the plant structure whilst the plant is in operation) – Is fitted in the most appropriate location on machine to maximise visibility without risking continual damage. NOTE: more than one beacon may be fitted to meet these criteria.',
      references: 'ISO20474-',
    },
  },

  // ─── MACHINE FRONT ───────────────────────────────────────────────────────
  {
    id: 'q_front_blade_label',
    shortLabel: 'Front grader blade — crush zone hazard label both sides',
    text: 'Does the front grader blade have a clear and legible hazard warning label re: crush zone, keep clear, which is visible from both sides of the item of plant? (answer n/a if this item of plant does not have a front grader blade)',
    surveyGroup: 'Machine Front',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant does not have a front grader blade',
    treatment: {
      name: 'Front Grader Blade Label',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'MEDIUM', value: 13 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The front blade on this item of plant is reported/observed as fitted with a hazard warning label re: crush zone, keep clear. This label must be present and kept serviceable and verified by the operator/owner at all times.',
      references: 'AS1319- , ISO20474-',
    },
  },

  // ─── ENGINE ──────────────────────────────────────────────────────────────
  {
    id: 'q_engine_guards',
    shortLabel: 'Engine fan, alternator belts, pulleys and gears — permanently guarded',
    text: 'Do the engine fan, alternator belts, pulleys and gears have a sturdy permanently attached guard(s)?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Engine Guards',
      hazards: ['ENTANGLEMENT'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The engine fan and alternator belts, pulleys and gears are guarded. These guards must be present and kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1601',
    },
  },
  {
    id: 'q_engine_guard_label',
    shortLabel: 'Engine guards — label: "do not open/remove unless engine off and stopped"',
    text: 'Do all engine guards have a clear and legible hazard warning label present which states that the guard must not be opened or removed unless the engine is not running and all moving parts have stopped?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Engine Guard Label',
      hazards: ['ENTANGLEMENT', 'SHEARING', 'BURNS'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'MEDIUM', value: 13 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The engine fan and alternator belts, pulleys and gears are guarded. These guards have clear legible hazard warning labels re do not open or remove guards while engine is running. These labels must be present, legible and easily seen at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201, AS1319-',
    },
  },
  {
    id: 'q_exhaust_guarded',
    shortLabel: 'Engine exhaust guarded/located to prevent injury and fire',
    text: 'Is the engine exhaust guarded/located to prevent injury to any person and control the risk of initiating a fire?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Exhaust',
      hazards: ['FIRE', 'BURNS'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The engine exhaust on this item of plant is located/fitted with a guard to prevent injury to any person and control the risk of initiating a fire. Guards must be present, kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'q_engine_bay_access',
    shortLabel: 'Engine bay access — slip resistant, 3 points of contact',
    text: 'Is this item of plant fitted with engine bay access steps, ladder, rungs etc. (answer N/A if engine can be safely accessed when standing on the ground), if so are they slip resistant, free from damage, with three points of contact available at all times?',
    surveyGroup: 'Engine',
    allowNA: true,
    naCondition: 'Answer N/A if engine can be safely accessed when standing on the ground',
    treatment: {
      name: 'Engine Bay Access',
      hazards: ['FALLING', 'SLIPPING', 'TRIPPING'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'Safe access and egress to the engine bay/work area(s) must be maintained at all times whilst this item of plant is in operation. It must be non slip, free from damage, located at a height so as to not cause undue body stresses and strains with three points of contact available to personnel at all times. All personnel must – 1. Always face the item of plant during access and egress. 2. Always maintain three points of contact during access and egress. 3. Never carry an object(s) in his/her hand(s) during access and egress. 4. Never jump off machine.',
      references: 'AS5327',
    },
  },

  // ─── BATTERY ─────────────────────────────────────────────────────────────
  {
    id: 'q_battery_constrained',
    shortLabel: 'Batteries constrained — sturdy cover, ventilated, terminals protected',
    text: 'Are all batteries fitted to this item of plant constrained to prevent displacement & fitted with a permanent sturdy cover which allows for ventilation & ensures the terminals are protected?',
    surveyGroup: 'Battery',
    allowNA: false,
    treatment: {
      name: 'Battery Cover',
      hazards: ['ELECTRIC SHOCK', 'BURNS'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All batteries fitted to this item of plant are constrained to prevent displacement & fitted with a permanent sturdy cover which allows for ventilation & ensures the terminals are protected. The constraint and cover must be present and kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'q_battery_isolator',
    shortLabel: 'Battery isolation switch — clearly marked and lockable in off position',
    text: 'Is this item of plant fitted with a fully functional battery isolation switch that is clearly and legibly marked and lockable in the off position?',
    surveyGroup: 'Battery',
    allowNA: false,
    treatment: {
      name: 'Battery Isolator',
      hazards: ['NON COMPLIANCE'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional battery isolation switch that is clearly and legibly marked and lockable in the off position. The battery isolation switch must remain clearly and legibly marked and lockable at all times whilst this item of plant is in operation.',
      references: 'AS20474.1',
    },
  },

  // ─── HYDRAULICS ──────────────────────────────────────────────────────────
  {
    id: 'q_hydraulic_hoses_present',
    shortLabel: 'Hydraulic hoses present on this item of plant',
    text: 'Does this item of plant have hydraulic hoses? (You cannot answer n/a to this question)',
    surveyGroup: 'Hydraulics',
    allowNA: false,
    treatment: {
      name: 'Hydraulic Hoses',
      hazards: ['STRIKING', 'BURNS'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant has hydraulic hoses. These hoses must be inspected each day or before each use for wear and tear. If there are visible signs of wear, immediate action must be taken to control the risk arising from this wear. These inspections must be documented. Hydraulic fluid at high pressure can penetrate the skin, never use any part of your body to check for leaks. If oil penetrates the skin seek medical advice immediately. Always use a piece of cardboard or similar to check for suspected leaks. Always wear appropriate gloves when handling hydraulic hoses. Hydraulic pressure can be stored and is a hazard. Always connect and disconnect hydraulic hoses as per the manufacturer\'s manual.',
      references: 'AS4024, AS2671',
    },
  },
  {
    id: 'q_hydraulic_hoses_damage_free',
    shortLabel: 'Hydraulic hoses free from damage and protected where contacting plant',
    text: 'Are all hydraulic hoses and fittings free from damage and protected from damage at all points where the hoses come into contact with the plant structure? (if this item of plant does not have hydraulic hoses answer n/a)',
    surveyGroup: 'Hydraulics',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant does not have hydraulic hoses',
    treatment: {
      name: 'Hydraulic Damage',
      hazards: ['STRIKING', 'BURNS'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The hydraulic hoses to this item of plant are free from damage and protected against damage arising from contact with the plant structure. Ensure that hoses are free from damage and that protection is in place at all times whilst this item of plant is in operation. Inspection of the hydraulic hoses and protection system should be conducted regularly and documented as part of your plant safety programme.',
      references: 'AS4024, ISO4413, AS2671',
    },
  },
  {
    id: 'q_hydraulic_hoses_shielded',
    shortLabel: 'Hydraulic hoses located/shielded to protect operator from failure',
    text: 'Are all hydraulic hoses and fittings located or shielded to protect the operator from injury due to fluid jet or movement (whiplash) of the hose as a result of leakage or component failure?',
    surveyGroup: 'Hydraulics',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant does not have hydraulic hoses',
    treatment: {
      name: 'Hydraulic Hose Failure Shield',
      hazards: ['STRIKING', 'BURNS'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a sturdy, permanent shield(s) between the hydraulic hoses and any body parts of the operator to provide protection during a hose or component failure. This shield(s) must be present and kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS4024, ISO4413, AS2671',
    },
  },

  // ─── CHASSIS ─────────────────────────────────────────────────────────────
  {
    id: 'q_fire_extinguisher',
    shortLabel: 'Fire extinguisher — mounted adjacent operator area, tagged per AS 1851',
    text: 'Is there a fire extinguisher mounted adjacent to the operators area, tagged and inspected periodically as prescribed by AS 1851?',
    surveyGroup: 'Chassis',
    allowNA: false,
    treatment: {
      name: 'Fire Extinguisher',
      hazards: ['FIRE'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with an approved and maintained fire extinguisher. Fire extinguisher(s) must be present and kept serviceable and verified by the operator/owner at all times. They must be readily accessible to the operator. Regular inspections must also be carried out in accordance with the manufacturer\'s requirements and AS 1851 – 1995.',
      references: 'AS1851',
    },
  },
  {
    id: 'q_engine_compartment_enclosed',
    shortLabel: 'Engine/motor compartment fully enclosed and lockable',
    text: 'Is the engine/motor compartment fully enclosed and lockable to prevent unauthorised access?',
    surveyGroup: 'Chassis',
    allowNA: false,
    treatment: {
      name: 'Engine/Motor Compartment',
      hazards: ['NON COMPLIANCE'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The engine/motor compartment is fully enclosed and lockable to prevent unauthorised access. A code/key must only be given to those that have appropriate experience or training. These points of access must remain fully lockable at all times whilst this item of plant is in operation.',
      references: 'AS20474.1',
    },
  },
  {
    id: 'q_grader_blade_label',
    shortLabel: 'Grader blade — crush zone hazard label visible both sides',
    text: 'Does the grader blade have a clear and legible hazard warning label re: crush zone, keep clear, which is visible from both sides of this item of plant?',
    surveyGroup: 'Chassis',
    allowNA: false,
    treatment: {
      name: 'Grader Blade Label',
      hazards: ['CRUSHING', 'COLLISION'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'MEDIUM', value: 13 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The grader blade on this item of plant is reported/observed as fitted with a hazard warning label re: crush zone, keep clear. This label must be present and kept serviceable and verified by the operator/owner at all times.',
      references: 'AS1319- , ISO20474-',
    },
  },
  {
    id: 'q_tank_id_labels',
    shortLabel: 'All tanks labelled with contents and controls',
    text: 'Do the tank(s) on this item of plant carry a clear, legible label identifying their contents, and if appropriate any necessary controls re: those contents? (includes radiator, hydraulic, water and petrol/diesel tanks)',
    surveyGroup: 'Chassis',
    allowNA: false,
    treatment: {
      name: 'Tank ID Label',
      hazards: ['POISONING', 'EXPLOSION', 'BURNS'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The tank(s) on this item of plant have clear, legible label(s) identifying their contents, and if appropriate any necessary controls re: the contents. These must be present, clear and legible at all times. (this includes radiator, hydraulic, water and petrol/diesel tanks etc.)',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'q_articulated_joint_label',
    shortLabel: 'Articulated joint — crush zone hazard labels both sides',
    text: 'Do both sides of the articulated joint carry clear hazard warning labels re: crush zone, keep clear?',
    surveyGroup: 'Chassis',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant does not have an articulated joint',
    treatment: {
      name: 'Articulated Joint Crush Label',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant has clear hazard warning labels re: crush zone, keep clear, that are attached to each side of the articulated joint. These must be present, clear and legible at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201, ISO20474-',
    },
  },
  {
    id: 'q_articulated_joint_locking',
    shortLabel: 'Articulated joint — locking device and instruction label both sides',
    text: 'Does the item of plant have either a locking arm fitted to the articulated joint or cylinder locking devices available and is there a clear, legible instruction label present on both sides of the articulated joint which states that either of these devices must be engaged during any maintenance to the articulated joint?',
    surveyGroup: 'Chassis',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant does not have an articulated joint',
    treatment: {
      name: 'Articulated Joint Locking Device',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a safety locking device to the articulated joint (either a locking arm or cylinder locking devices) and clear, legible instruction labels on both sides of the articulated joint which state that either of these devices must be engaged during any maintenance to the articulated joint. These must be present, serviceable and employed at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201, AS1319-',
    },
  },

  // ─── TYRES / WHEELS ──────────────────────────────────────────────────────
  {
    id: 'q_tyres_functional',
    shortLabel: 'All tyres and wheel components fully functional',
    text: 'Are all tyres and wheel components fully functional?',
    surveyGroup: 'Tyres/Wheels',
    allowNA: false,
    treatment: {
      name: 'Tyres',
      hazards: ['INSTABILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The tyres and wheel components must be inspected as part of a "pre start" checklist. These inspections must be documented as part of your plant safety programme.',
      references: 'ISO31000',
    },
  },

  // ─── DRAWBAR / TOW POINT ─────────────────────────────────────────────────
  {
    id: 'q_drawbar_label',
    shortLabel: 'Drawbar — hazard warning label re: maximum towing capacity',
    text: 'If this item of plant has a drawbar, is there a clear hazard warning label adjacent the drawbar/tow hitch re: maximum towing capacity? (answer n/a if this item of plant does not have a drawbar/tow hitch)',
    surveyGroup: 'Drawbar/Tow Point',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant does not have a drawbar/tow hitch',
    treatment: {
      name: 'Drawbar Capacity Label',
      hazards: ['INCORRECT OPERATION', 'OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        "The item of plant has a drawbar and a hazard warning label attached adjacent the drawbar/tow hitch re: maximum towing capacity, crushing, keep clear. It must be present and kept serviceable and verified by the operator/owner at all times.",
      references: 'ISO31000',
    },
  },
  {
    id: 'q_recovery_tow_label',
    shortLabel: 'Recovery tow point — hazard label with manufacturer towing instructions',
    text: 'Is this item of plant fitted with a recovery tow point (answer n/a if no recovery tow point), if so is there a hazard warning label adjacent which states "Recovery tow point - Read manufacturer\'s towing instructions before towing"?',
    surveyGroup: 'Drawbar/Tow Point',
    allowNA: true,
    naCondition: 'Answer N/A if no recovery tow point',
    treatment: {
      name: 'Recovery Point Label',
      hazards: ['COLLISION'],
      prelimRating: { label: 'MEDIUM', value: 9 },
      residualRating: { label: 'LOW', value: 5 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant is reported/observed as fitted with a hazard warning label adjacent the recovery tow point which states "Recovery tow point – Read manufacturer\'s towing instructions before towing". Failure to do so could result in DEATH or SERIOUS INJURY. This label must be clear and legible at all times whilst this item of plant is in operation.',
      references: 'ISO31000',
    },
  },

  // ─── MACHINE REAR ────────────────────────────────────────────────────────
  {
    id: 'q_ripper_label',
    shortLabel: 'Rippers — crush zone hazard label visible both sides',
    text: 'If this item of plant is fitted with rippers, do the rippers have a clear and legible hazard warning label re: crush zone, keep clear, which is visible from both sides of this item of plant? (If this item is not fitted with rippers then answer n/a)',
    surveyGroup: 'Machine Rear',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant is not fitted with rippers',
    treatment: {
      name: 'Ripper Crush Zone Label',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'MEDIUM', value: 13 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The rippers on this item of plant are reported/observed as fitted with a hazard warning label re: crush zone, keep clear. This label must be present and kept serviceable and verified by the operator/owner at all times.',
      references: 'AS/NZS4024.1201, ISO20474-',
    },
  },
  {
    id: 'q_roller_attachment',
    shortLabel: 'Roller attachment — meets all safety criteria (speed limiter, hydraulic release, visual indicator)',
    text: 'Is this item of plant fitted with a roller attachment to the rear ripper bar (e.g. a "Freeroll")? If so, does it meet the following criteria: 1. Does not exceed weight requirements 2. Has RIPPER/ROLLER mode selector 3. Has speed limit device to 20km/h in roller mode 4. Releases hydraulic pressure when brakes applied? (answer n/a if no roller attachment)',
    surveyGroup: 'Machine Rear',
    allowNA: true,
    naCondition: 'Answer N/A if no roller attachment is fitted',
    treatment: {
      name: 'Roller Attachment',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a roller attachment to the rear ripper bar (e.g. a "Freeroll"). Accordingly this item of plant meets the following criteria – 1. Roller does not exceed machine and ripper manufacturers weight requirements 2. Has a device in the operator cabin to select either RIPPER or ROLLER mode which is clearly labelled 3. When in Roller mode – (a) Has a visual system within clear view of the operator which provides verification that roller mode is selected (b) Has a device which limits the speed of the machine to 20 kmh/hr and (c) Has a device which releases hydraulic pressure in the ripper bar lift/lower cylinders when the service brakes are applied. All operators must be familiar with these devices prior to operation. These safety devices must be in place at all times whilst this item of plant is in operation.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_vehicle_reversing_label',
    shortLabel: '"Vehicle Frequently Reversing" hazard warning label — rear of plant',
    text: 'Does this item of plant have a clear hazard warning label fitted to the rear re: Vehicle Frequently Reversing?',
    surveyGroup: 'Machine Rear',
    allowNA: false,
    treatment: {
      name: 'Vehicle Frequently Reversing',
      hazards: ['CRUSHING', 'STRIKING', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The rear of this item of plant has a hazard warning label re: vehicle frequently reversing. It must be present and kept serviceable and verified by the operator/owner at all times.',
      references: 'ISO20474-',
    },
  },

  // ─── PLANT CONDITION ─────────────────────────────────────────────────────
  {
    id: 'q_free_from_leaks',
    shortLabel: 'Free from major leaks (engine, transmission, hydraulics, etc.)',
    text: 'Is this item of plant free from any major leaks? (this includes engine, transmission, cooling system, air, fuel, drive line, wheel hubs, steering and hydraulics)',
    surveyGroup: 'Plant Condition',
    allowNA: false,
    treatment: {
      name: 'Major Fluid Leaks',
      hazards: ['OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'LOW', value: 2 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'This item of plant must remain free from leaks at all times whilst in operation (this includes engine, transmission, cooling system, air, fuel, drive line, wheel hubs, steering and hydraulics). Development of a major leak will require this item of plant to be stood-down until repaired. Minor leaks detected must be repaired within 1-14 days.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_original_condition',
    shortLabel: 'Plant in original condition — no modifications or upgrades',
    text: 'Is this item of plant in original condition, ie free from any form of modification or upgrade? (If you answer NO, please document location, type of modification and date in the assessor comments)',
    surveyGroup: 'Plant Condition',
    allowNA: false,
    treatment: {
      name: 'Plant Modification',
      hazards: ['OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'LOW', value: 2 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The plant is in original condition.',
      references: 'ISO31000',
    },
  },
  {
    id: 'q_free_structural_damage',
    shortLabel: 'Free from structural damage (cracks, bends, damage to structural components)',
    text: 'Is this item of plant free from any structural damage? E.g. cracks in frames/chassis (current or repaired), bends or damage to structural components, etc.',
    surveyGroup: 'Plant Condition',
    allowNA: false,
    treatment: {
      name: 'Structural Integrity',
      hazards: ['CURRENT OR PREVIOUS STRUCTURAL DAMAGE'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Regular checks for structural damage must be undertaken. Look for cracks in frames/chassis (current or repaired), bends or damage to structural components, etc.',
      references: 'ISO31000',
    },
  },
];

export const SURVEY_GROUPS = [
  'Information',
  'Brakes',
  'Cabin/Work Area',
  'Controls',
  'Operator Protective Guards',
  'PPE',
  'Lighting',
  'Machine Front',
  'Engine',
  'Battery',
  'Hydraulics',
  'Chassis',
  'Tyres/Wheels',
  'Drawbar/Tow Point',
  'Machine Rear',
  'Plant Condition',
] as const;
