import type { Question } from './types';

export const POSI_TRACK_SURVEY_GROUPS = [
  'Information',
  'Cabin/Work Area',
  'Controls',
  'Operator Protective Guards',
  'PPE',
  'Lighting',
  'Engine',
  'Battery',
  'Hydraulics',
  'Loader Arms & Attachment',
  'Undercarriage & Tracks',
  'Plant Condition',
] as const;

export const POSI_TRACK_QUESTIONS: Question[] = [
  // ─── INFORMATION ─────────────────────────────────────────────────────────
  {
    id: 'pt_q_ops_handbook',
    shortLabel: "Manufacturer's operation handbook available",
    text: "Is the manufacturer's operation handbook available for this item of plant? (You cannot answer N/A)",
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Operation Handbook',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        "The manufacturer's operation handbook has been supplied for this item of plant. This handbook must be available at all times to all potential operators and supervisory staff. All potential operators must read and be familiar with this handbook prior to operating. A complete risk assessment/Job Safety Analysis must be undertaken covering all operating processes and environments associated with this item of plant. SWMS should be produced for specific tasks associated with use of this item of plant.",
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'pt_q_maint_manual',
    shortLabel: "Manufacturer's maintenance manual(s) available",
    text: "Is the manufacturer's maintenance manual(s) available for this item of plant? (You cannot answer N/A)",
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Maintenance Manual',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        "The manufacturer's maintenance manual(s) has been supplied for this item of plant. These manual(s) must be available at all times to all users and maintenance staff of this item of plant. All users and maintenance staff must read and be familiar with these handbook(s) prior to maintaining or repairing this item of plant. A complete risk assessment/JSEA must be undertaken covering all inspection, maintenance, servicing and transportation requirements of this piece of plant prior to use.",
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'pt_q_service_records',
    shortLabel: 'Service and maintenance records available',
    text: 'Are the service and maintenance records available for this item of plant? (You cannot answer N/A)',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Service Records',
      hazards: ['OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Service and maintenance records are available for this item of plant. These records must continue to be managed and available at all times as part of your service and maintenance programme. (This programme includes the undertaking of regular inspections of the item of plant with specific reference to all OEM prescribed, scheduled and non scheduled service and maintenance requirements).',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'pt_q_preop_checklist',
    shortLabel: 'Pre-operational safety checklist available',
    text: 'Is a pre-operational safety checklist available for this Posi Track / compact track loader? (You cannot answer N/A)',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Pre-op Checklist Posi Track',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'A pre-operational checklist is available for this Posi Track / compact track loader. All operators must complete this checklist prior to operating.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'pt_q_sop',
    shortLabel: 'Safe Operation Procedures available',
    text: 'Are Safe Operation Procedures available for this Posi Track / compact track loader? (You cannot answer N/A)',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'SOP Posi Track',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'Safe Operation Procedures are available for this Posi Track / compact track loader. The information in the Safe Operation Procedures must be followed at all times whilst operating.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'pt_q_operator_qualified',
    shortLabel: 'Operators qualified, trained, and experienced',
    text: 'Are all persons who operate this item of plant qualified, trained and experienced to do so, and where necessary do they hold the relevant certification/license?',
    surveyGroup: 'Information',
    allowNA: false,
    treatment: {
      name: 'Operator Competency',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'CRITICAL', value: 24 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'Only persons who are qualified, trained and experienced and/or hold the relevant certification/license can operate this item of plant. If there is not a competent/licensed person available for operation of this item of plant then only persons who are supervised by a competent/licensed person can operate this item of plant.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'pt_q_swms_loading',
    shortLabel: 'SWMS/SOP for loading and unloading available',
    text: 'Are specific guidelines/SWMS/SOP available for loading and unloading this item of plant to & from the load deck of a truck or trailer?',
    surveyGroup: 'Information',
    allowNA: true,
    treatment: {
      name: 'SWMS Loading/Unloading',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DELIVERY',
      treatmentText:
        'Ensure that all operators follow approved SWMS/SOP when loading and unloading this machine to and from a flat top truck or trailer, low loader or tilt tray.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },
  {
    id: 'pt_q_swms_restraint',
    shortLabel: 'SWMS/SOP for load restraint available',
    text: 'Are specific load restraint guidelines/SWMS/SOP available when restraining this item of plant on to the load deck of a truck or trailer?',
    surveyGroup: 'Information',
    allowNA: true,
    treatment: {
      name: 'SWMS Load Restraint',
      hazards: ['CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DELIVERY',
      treatmentText:
        'Ensure that all operators follow the approved SWMS/SOP when restraining this machine for transport.',
      references: 'Work Health & Safety Act & Regulations- , Occupational Health & Safety Act & Regulations',
    },
  },

  // ─── CABIN / WORK AREA ───────────────────────────────────────────────────
  {
    id: 'pt_q_cabin_access_steps',
    shortLabel: 'Cabin access/egress — slip-resistant steps, 3 points of contact',
    text: 'Does the cabin/work area access and egress have slip resistant steps that are free from damage, located at the appropriate height to allow safe access and egress without undue bodystressing/strains, with three points of contact available at all times?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Operator Work Area Access/Egress',
      hazards: ['SLIPPING'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'Safe access and egress to the cabin/work area(s) must be maintained at all times whilst this item of plant is in operation. It must be non slip, free from damage, located at a height so as to not cause undue body stresses and strains with three points of contact available to personnel at all times. All personnel must – 1. Always face the item of plant during access and egress. 2. Always maintain three points of contact during access and egress. 3. Never carry an object(s) in his/her hand(s) during access and egress. 4. Never jump off machine.',
      references: 'AS5327',
    },
  },
  {
    id: 'pt_q_cabin_access_label',
    shortLabel: 'Cabin access — instruction label present (face machine, 3 points of contact)',
    text: 'Does the cabin/work area access and egress have an instruction label adjacent to advise all personnel of the following - 1. Always face the item of plant during access and egress. 2. Always maintain three points of contact during access and egress. 3. Ensure steps are clean. 4. Never jump off machine?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Access/Egress Instruction Label',
      hazards: ['FALLING', 'SLIPPING'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'An instruction label is fitted adjacent access/egress areas to advise all personnel of the following – 1. Always face the item of plant during access and egress. 2. Always maintain three points of contact during access and egress. 3. Ensure the steps are clean. 4. Never jump off machine. This label must be clear and legible at all times whilst this item of plant is in operation.',
      references: 'ISO31000',
    },
  },
  {
    id: 'pt_q_emergency_exits_compliance',
    shortLabel: 'Emergency exits — labelled, instructions clear, tools available',
    text: 'Do the emergency exits for this item of plant meet the following requirements - 1. Clearly and legibly labelled 2. Instructions for use are clear and legible and located adjacent the exit 3. Any required tools required for use are available e.g. Emergency hammers? (Answer NA if no emergency exits due to no cabin)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if no emergency exits due to no cabin',
    treatment: {
      name: 'Emergency Exits',
      hazards: ['ENTRAPMENT'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The emergency exits for this item of plant meet the following requirements – 1. Clearly and legibly labelled 2. Instructions for use are clear and legible and located adjacent the exit 3. Any required tools required for use are available e.g. Emergency hammers. These exits must be legibly labelled and kept serviceable and verified by the operator/owner at all times whenever the item of plant is manned, whether during operation or maintenance activities.',
      references: 'ISO31000',
    },
  },
  {
    id: 'pt_q_windows_screens',
    shortLabel: 'Cabin windows — present, clean, safety glass, no cracks',
    text: 'Are all cabin/work area windows and screens present, clean, constructed from safety glass and free from cracks and other damage? (N.B. Perspex is not acceptable)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if no cabin',
    treatment: {
      name: 'Windows & Screens',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Ensure the cabin/work area safety glass windows and screens are kept clean and free from cracks and other damage at all times whilst this item of plant is in use.',
      references: 'AS/NZS4024.1201, ISO20474-',
    },
  },
  {
    id: 'pt_q_windscreen_wipers',
    shortLabel: 'Windscreen wipers and washers fully functional',
    text: 'Is this item of plant fitted with fully functional windscreen wipers and washers? (if this item of plant does not have a screen then answer n/a)',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if this item of plant does not have a screen',
    treatment: {
      name: 'Windscreen Wipers',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with fully functional windscreen wipers and washers. These must be kept serviceable and verified by the operator/owner at all times.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_loose_items',
    shortLabel: 'Operator work area — free from loose items',
    text: 'Is the operator work area free from loose items, in particular items that could restrict the operation of foot controls (pedals)?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Loose Items - Operator Work Area',
      hazards: ['OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The operator work area must remain free from loose items at all times and in particular must be free from any items which could restrict the operation of foot controls (pedals). This is the responsibility of the operator.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_work_area_floors',
    shortLabel: 'Work area floors — safe, no holes or gaps',
    text: 'Are the operator work area floor(s) safe for the purpose, free from holes, damage and raised edges?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Work Area Floors',
      hazards: ['SLIPPING', 'FALLING'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The operator work area floors must be safe for the purpose and must remain free from holes, damage and raised edges at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_operator_mirrors',
    shortLabel: 'Operator mirrors — clean, free from damage, correctly positioned',
    text: 'Are the operator mirror(s) clean, free from damage and correctly positioned?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if no mirrors fitted',
    treatment: {
      name: 'Operator Mirrors',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The operator mirror(s) on this item of plant must remain clean, free from damage and correctly positioned at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_operator_seat',
    shortLabel: 'Operator seat — adjustable, suspension functional, correctly positioned',
    text: 'Is the operator seat fully adjustable, is the suspension fully functional, and is the seat correctly positioned to provide full control of this item of plant?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Operator Seat',
      hazards: ['VIBRATION'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The operator seat must be fully adjustable and the suspension must remain fully functional at all times whilst this item of plant is in operation. The seat must be correctly adjusted for the operator to have full control of this item of plant.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_seat_belt',
    shortLabel: 'Seat belt — fitted, functional, operator must wear at all times',
    text: 'Is this item of plant fitted with a fully functional seat belt and is the operator required to wear it at all times?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Seat Belt',
      hazards: ['ROLLOVER'],
      prelimRating: { label: 'CRITICAL', value: 24 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a seat belt. The seat belt must be worn by the operator at all times whilst this item of plant is in operation. The seat belt must be kept serviceable and verified by the operator/owner at all times.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_air_conditioning',
    shortLabel: 'Air conditioning functional (if fitted)',
    text: 'If this item of plant is fitted with air conditioning, is it fully functional?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if no air conditioning fitted',
    treatment: {
      name: 'Air Conditioning',
      hazards: ['HEAT STRESS'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with air conditioning. The air conditioning system must be kept serviceable and verified by the operator/owner at all times when conditions require its use.',
      references: 'ISO31000',
    },
  },
  {
    id: 'pt_q_no_phone_label',
    shortLabel: '"No mobile phone use while operating" label present',
    text: 'Is there a label fitted to this item of plant advising operators of the prohibition of mobile phone use whilst operating this item of plant?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: false,
    treatment: {
      name: 'Phone Use Label',
      hazards: ['COLLISION', 'POOR VISIBILITY'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'OPERATION',
      treatmentText:
        'A label is fitted advising of the prohibition of mobile phone use whilst operating this item of plant. This label must be present, clear and legible at all times.',
      references: 'ISO31000',
    },
  },
  {
    id: 'pt_q_rear_camera',
    shortLabel: 'Rear-view / proximity camera fitted and functional',
    text: 'Is this item of plant fitted with a fully functional rear-view camera or proximity detection system?',
    surveyGroup: 'Cabin/Work Area',
    allowNA: true,
    naCondition: 'Answer N/A if no camera or proximity system fitted',
    treatment: {
      name: 'Rear Camera',
      hazards: ['COLLISION', 'CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a rear-view camera or proximity detection system. This must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },

  // ─── CONTROLS ─────────────────────────────────────────────────────────────
  {
    id: 'pt_q_handrails',
    shortLabel: 'Handrails/grab handles — fitted, secure, free from damage',
    text: 'Does this item of plant have handrails/grab handles that are fitted, secure and free from damage?',
    surveyGroup: 'Controls',
    allowNA: true,
    naCondition: 'Answer N/A if no handrails/grab handles fitted',
    treatment: {
      name: 'Handrails',
      hazards: ['FALLING', 'SLIPPING'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The handrails/grab handles on this item of plant must be kept secure and free from damage at all times whilst this item of plant is in operation.',
      references: 'AS5327',
    },
  },
  {
    id: 'pt_q_warning_horn',
    shortLabel: 'Warning device (horn) — fitted and functional',
    text: 'Is this item of plant fitted with a fully functional warning device (horn)?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Warning Device (Horn)',
      hazards: ['COLLISION', 'CRUSHING'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional warning device (horn). The warning device must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_controls_ergonomics',
    shortLabel: 'Controls — ergonomically positioned, accessible, functional',
    text: 'Are all operator controls ergonomically positioned, easily accessible from the operator seat and fully functional?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Controls Ergonomics',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All operator controls must remain ergonomically positioned, easily accessible from the operator seat and fully functional at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_control_labels',
    shortLabel: 'Controls — correctly and clearly labelled',
    text: 'Are all operator controls correctly and clearly labelled?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Control Labels',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All operator controls must be correctly and clearly labelled at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_reverse_alarm',
    shortLabel: 'Reverse movement alarm — fitted and functional',
    text: 'Is this item of plant fitted with a fully functional reverse movement alarm?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Reverse Movement Alarm',
      hazards: ['COLLISION', 'CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional reverse movement alarm. The reverse alarm must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201, ISO20474-',
    },
  },
  {
    id: 'pt_q_emergency_stop',
    shortLabel: 'Emergency stop/shutdown device — fitted and functional',
    text: 'Is this item of plant fitted with a fully functional emergency stop/shutdown device accessible from the operator seat?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Emergency Stop/Shutdown Device',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'CRITICAL', value: 24 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional emergency stop/shutdown device. This device must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_restricted_access',
    shortLabel: 'Restricted access switches (key, PIN, etc.) — fitted and functional',
    text: 'Is this item of plant fitted with fully functional restricted access device(s) (e.g. key switch, PIN device) that prevents unauthorised use?',
    surveyGroup: 'Controls',
    allowNA: false,
    treatment: {
      name: 'Restricted Access Switches',
      hazards: ['INCORRECT OPERATION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with restricted access device(s) that prevent unauthorised use. These devices must be kept serviceable and verified by the operator/owner at all times.',
      references: 'ISO31000',
    },
  },

  // ─── OPERATOR PROTECTIVE GUARDS ─────────────────────────────────────────
  {
    id: 'pt_q_rops_fitted',
    shortLabel: 'ROPS fitted, compliant, and undamaged',
    text: 'Is this item of plant fitted with a certified Roll Over Protective Structure (ROPS) that complies with relevant Australian standards, is free from damage, and has the compliance plate fitted?',
    surveyGroup: 'Operator Protective Guards',
    allowNA: false,
    treatment: {
      name: 'Earthmoving ROPS',
      hazards: ['ROLLOVER'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a certified ROPS. The ROPS must be regularly inspected and maintained and must be kept free from damage at all times whilst this item of plant is in operation. The ROPS compliance plate must be clearly legible.',
      references: 'ISO 12117-2, AS1636.1',
    },
  },
  {
    id: 'pt_q_rops_damage',
    shortLabel: 'ROPS free from damage — no cracks, bends or unauthorised modifications',
    text: 'Is the ROPS free from damage, including cracks, bends and unauthorised modifications?',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if no ROPS fitted',
    treatment: {
      name: 'ROPS Damage',
      hazards: ['ROLLOVER'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The ROPS on this item of plant must remain free from damage including cracks, bends and unauthorised modifications. Any damage to the ROPS will require the item of plant to be stood-down pending engineering assessment.',
      references: 'ISO 12117-2, AS1636.1',
    },
  },
  {
    id: 'pt_q_rops_label',
    shortLabel: 'ROPS label — fitted, clear and legible',
    text: 'Is the ROPS on this item of plant fitted with a label identifying it as a ROPS that is clearly and legibly labelled?',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if no ROPS fitted',
    treatment: {
      name: 'ROPS Label',
      hazards: ['ROLLOVER'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The ROPS on this item of plant is reported/observed as fitted with a label identifying it as a ROPS. This label must remain clear and legible at all times.',
      references: 'ISO 12117-2',
    },
  },
  {
    id: 'pt_q_rops_seatbelt_label',
    shortLabel: 'Seat belt label fitted to ROPS',
    text: 'Is there a label fitted to the ROPS advising operators to wear their seat belt at all times?',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if no ROPS fitted',
    treatment: {
      name: 'ROPS Seat Belt Label',
      hazards: ['ROLLOVER'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'A label is fitted to the ROPS advising operators to wear their seat belt at all times. This label must remain clear and legible at all times.',
      references: 'ISO 12117-2',
    },
  },
  {
    id: 'pt_q_fops_fitted',
    shortLabel: 'FOPS fitted and compliant',
    text: 'Is this item of plant fitted with a certified Falling Object Protective Structure (FOPS) that complies with relevant Australian standards?',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if FOPS is not required for this application',
    treatment: {
      name: 'FOPS General',
      hazards: ['FALLING OBJECT'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a certified FOPS. The FOPS must be regularly inspected and maintained at all times whilst this item of plant is in operation.',
      references: 'ISO 10262, AS1636.2',
    },
  },
  {
    id: 'pt_q_fops_level2',
    shortLabel: 'FOPS Level II fitted (where required for the application)',
    text: 'Where required by the application (e.g. demolition, working under suspended loads), is this item of plant fitted with a FOPS that meets Level II requirements?',
    surveyGroup: 'Operator Protective Guards',
    allowNA: true,
    naCondition: 'Answer N/A if Level II FOPS is not required for this application',
    treatment: {
      name: 'FOPS Level II',
      hazards: ['FALLING OBJECT'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a FOPS meeting Level II requirements. The FOPS must be regularly inspected and kept serviceable and verified by the operator/owner at all times.',
      references: 'ISO 10262 Level II',
    },
  },

  // ─── PPE ─────────────────────────────────────────────────────────────────
  {
    id: 'pt_q_hearing_protection_operator',
    shortLabel: 'Hearing protection label — fitted in operator area',
    text: 'Is there a hearing protection required label fitted in the operator work area?',
    surveyGroup: 'PPE',
    allowNA: false,
    treatment: {
      name: 'Hearing Protection Label - Operator',
      hazards: ['NOISE'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'OPERATION',
      treatmentText:
        'A hearing protection required label is fitted in the operator work area of this item of plant. This label must remain clear and legible at all times. All operators must wear appropriate hearing protection whilst operating this item of plant.',
      references: 'AS/NZS1270',
    },
  },
  {
    id: 'pt_q_hearing_protection_bystanders',
    shortLabel: 'Hearing protection label — fitted for bystanders/maintenance',
    text: 'Is there a hearing protection required label fitted to the exterior of the plant for the benefit of bystanders and maintenance staff?',
    surveyGroup: 'PPE',
    allowNA: false,
    treatment: {
      name: 'Hearing Protection Label - Bystanders',
      hazards: ['NOISE'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'OPERATION',
      treatmentText:
        'A hearing protection required label is fitted to the exterior of this item of plant. This label must remain clear and legible at all times. All persons near this item of plant whilst in operation must wear appropriate hearing protection.',
      references: 'AS/NZS1270',
    },
  },

  // ─── LIGHTING ────────────────────────────────────────────────────────────
  {
    id: 'pt_q_machine_lights',
    shortLabel: 'Machine lights — work lights functional',
    text: 'Are all machine work lights fitted to this item of plant fully functional?',
    surveyGroup: 'Lighting',
    allowNA: true,
    naCondition: 'Answer N/A if no work lights fitted',
    treatment: {
      name: 'Machine Lights',
      hazards: ['POOR VISIBILITY', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The machine work lights on this item of plant must be kept serviceable and verified by the operator/owner at all times. All lights must be fully functional before working in low-light conditions.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_beacon',
    shortLabel: 'Flashing/rotating beacon — fitted and functional',
    text: 'Is this item of plant fitted with a fully functional flashing/rotating beacon?',
    surveyGroup: 'Lighting',
    allowNA: true,
    naCondition: 'Answer N/A if no beacon fitted',
    treatment: {
      name: 'Beacon',
      hazards: ['COLLISION', 'CRUSHING'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional flashing/rotating beacon. The beacon must be kept serviceable and verified by the operator/owner at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },

  // ─── ENGINE ──────────────────────────────────────────────────────────────
  {
    id: 'pt_q_engine_guards',
    shortLabel: 'Engine guards — fitted, secure, free from damage',
    text: 'Are all engine guards fitted to this item of plant fitted correctly, secure and free from damage?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Engine Guards',
      hazards: ['BURNING', 'CRUSHING'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The engine guards on this item of plant must be kept fitted correctly, secure and free from damage at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_engine_guard_label',
    shortLabel: 'Engine guard label — hot surfaces warning present',
    text: 'Is there a hazard warning label fitted adjacent to or on the engine guards warning of hot surfaces?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Engine Guard Label',
      hazards: ['BURNING'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'A hot surfaces hazard warning label is fitted on or adjacent to the engine guards. This label must remain clear and legible at all times.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_exhaust',
    shortLabel: 'Exhaust — free from damage, directed away from operator',
    text: 'Is the exhaust system free from damage and directed away from the operator work area?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Exhaust',
      hazards: ['FUMES', 'BURNING'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The exhaust system must remain free from damage and must be directed away from the operator work area at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_engine_bay_access',
    shortLabel: 'Engine bay — access doors/panels functional and properly secured',
    text: 'Are all engine bay access doors and panels free from damage, functional and able to be properly secured in the open and closed position?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Engine Bay Access',
      hazards: ['FALLING', 'CRUSHING'],
      prelimRating: { label: 'MEDIUM', value: 12 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'All engine bay access doors and panels must be free from damage, functional and properly secured in the open and closed position at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_engine_motor_compartment',
    shortLabel: 'Fire extinguisher — fitted, charged and accessible',
    text: 'Is this item of plant fitted with a fully charged, in-date fire extinguisher that is easily accessible to the operator?',
    surveyGroup: 'Engine',
    allowNA: false,
    treatment: {
      name: 'Engine/Motor Compartment',
      hazards: ['FIRE'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'This item of plant must be fitted with a fully charged, in-date fire extinguisher that is easily accessible to the operator at all times. The fire extinguisher must be regularly inspected and maintained.',
      references: 'AS/NZS1841',
    },
  },

  // ─── BATTERY ─────────────────────────────────────────────────────────────
  {
    id: 'pt_q_battery_cover',
    shortLabel: 'Battery cover — fitted and secure',
    text: 'Is the battery fitted with a cover that is secured in place?',
    surveyGroup: 'Battery',
    allowNA: false,
    treatment: {
      name: 'Battery Cover',
      hazards: ['ELECTRICAL'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The battery on this item of plant must be fitted with a cover that is secured in place at all times whilst this item of plant is in operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_battery_isolator',
    shortLabel: 'Battery isolator — fitted and functional',
    text: 'Is this item of plant fitted with a fully functional battery isolator?',
    surveyGroup: 'Battery',
    allowNA: false,
    treatment: {
      name: 'Battery Isolator',
      hazards: ['ELECTRICAL', 'FIRE'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a fully functional battery isolator. The battery isolator must be kept serviceable and verified by the operator/owner at all times. The battery isolator must be engaged whenever the plant is not in operation.',
      references: 'AS/NZS4024.1201',
    },
  },

  // ─── HYDRAULICS ──────────────────────────────────────────────────────────
  {
    id: 'pt_q_hydraulic_hoses',
    shortLabel: 'Hydraulic hoses and fittings — free from damage, leaks and chafing',
    text: 'Are all hydraulic hoses and fittings free from damage, leaks and chafing, and correctly routed and supported?',
    surveyGroup: 'Hydraulics',
    allowNA: false,
    treatment: {
      name: 'Hydraulic Hoses',
      hazards: ['INJECTION', 'FIRE', 'SLIPPING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'All hydraulic hoses and fittings must be free from damage, leaks and chafing and correctly routed and supported at all times. Any damage to hydraulic hoses must be repaired immediately. Personnel must never use their hands to check for hydraulic leaks.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_hydraulic_damage',
    shortLabel: 'Hydraulic system — free from damage and contamination',
    text: 'Is the hydraulic system free from damage and contamination?',
    surveyGroup: 'Hydraulics',
    allowNA: false,
    treatment: {
      name: 'Hydraulic Damage',
      hazards: ['INJECTION', 'OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The hydraulic system must remain free from damage and contamination at all times. The hydraulic fluid level and quality must be regularly checked and maintained.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_hydraulic_hose_shield',
    shortLabel: 'Hydraulic hose failure shield — fitted (where required)',
    text: 'Where hydraulic hoses are routed in proximity to high-temperature components (e.g. exhaust), are appropriate hose failure shields fitted?',
    surveyGroup: 'Hydraulics',
    allowNA: true,
    naCondition: 'Answer N/A if hose failure shields are not required for this application',
    treatment: {
      name: 'Hydraulic Hose Failure Shield',
      hazards: ['INJECTION', 'FIRE'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with hydraulic hose failure shields where required. These shields must be kept in place and serviceable and verified by the operator/owner at all times.',
      references: 'AS/NZS4024.1201',
    },
  },

  // ─── LOADER ARMS & ATTACHMENT ────────────────────────────────────────────
  {
    id: 'pt_q_loader_arms_condition',
    shortLabel: 'Loader arms — free from cracks, damage and deformation',
    text: 'Are the loader arms (lift arms) free from cracks, visible damage and structural deformation?',
    surveyGroup: 'Loader Arms & Attachment',
    allowNA: false,
    treatment: {
      name: 'Loader Arms Structural Condition',
      hazards: ['STRUCTURAL FAILURE', 'CRUSHING'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The loader arms must remain free from cracks, damage and structural deformation at all times. Regular inspections must be undertaken. Any cracks or structural damage will require the item of plant to be stood-down pending engineering assessment.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_loader_attachment_pins',
    shortLabel: 'Loader attachment pins — present, greased and retained',
    text: 'Are all loader arm and attachment pins present, adequately greased/lubricated and correctly retained (no missing or loose pins)?',
    surveyGroup: 'Loader Arms & Attachment',
    allowNA: false,
    treatment: {
      name: 'Loader Attachment Pins',
      hazards: ['STRUCTURAL FAILURE', 'CRUSHING'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'All loader arm and attachment pins must be present, adequately greased/lubricated and correctly retained at all times. Missing or loose pins must be rectified before operation. Pin conditions must be regularly checked and documented.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_bucket_condition',
    shortLabel: 'Bucket/attachment — structurally sound, no cracks or deformation',
    text: 'Is the bucket (or fitted attachment) structurally sound and free from cracks, deformation or excessive wear?',
    surveyGroup: 'Loader Arms & Attachment',
    allowNA: false,
    treatment: {
      name: 'Bucket/Attachment Condition',
      hazards: ['STRUCTURAL FAILURE', 'CRUSHING'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'The bucket/attachment must remain structurally sound and free from cracks, deformation or excessive wear at all times. Regular inspections must be undertaken and any structural issues rectified before operation.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_quick_attach_safety',
    shortLabel: 'Quick attach — secondary safety locking device fitted and engaged',
    text: 'If this machine is fitted with a quick attach system, does it have a secondary safety locking device (pin, latch or equivalent) that must be manually engaged before operation, and is it engaged?',
    surveyGroup: 'Loader Arms & Attachment',
    allowNA: true,
    naCondition: 'Answer N/A if no quick attach fitted',
    treatment: {
      name: 'Quick Attach Safety Device',
      hazards: ['CRUSHING', 'STRUCTURAL FAILURE', 'FALLING OBJECT'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a quick attach system that has a secondary safety locking device. The secondary safety locking device must be manually engaged every time an attachment is changed and must remain engaged throughout operation. The operator must visually verify engagement before commencing work.',
      references: 'AS4772, AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_load_overhead_label',
    shortLabel: 'Load-over-head crush zone hazard warning label fitted',
    text: 'Is there a hazard warning label fitted to this item of plant warning of the load-over-head crush zone (never raise load over operator/cab)?',
    surveyGroup: 'Loader Arms & Attachment',
    allowNA: false,
    treatment: {
      name: 'Load Over Head Crush Zone Label',
      hazards: ['CRUSHING', 'FALLING OBJECT'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'This item of plant is reported/observed as fitted with a load-over-head crush zone hazard warning label. This label must remain clear and legible at all times. Operators must never raise the load over the cab or operator area.',
      references: 'AS/NZS4024.1201',
    },
  },

  // ─── UNDERCARRIAGE & TRACKS ──────────────────────────────────────────────
  {
    id: 'pt_q_track_tension',
    shortLabel: 'Track tension — correctly adjusted per manufacturer specification',
    text: 'Are the tracks correctly tensioned as per the manufacturer specification? (Check for excessive sagging or over-tensioning)',
    surveyGroup: 'Undercarriage & Tracks',
    allowNA: false,
    treatment: {
      name: 'Track Tension',
      hazards: ['OPERATIONAL MALFUNCTION', 'ROLLOVER'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'LOW', value: 6 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Track tension must be maintained at the correct specification at all times. Incorrect track tension will cause accelerated undercarriage wear and may cause derailment. Track tension must be checked and adjusted regularly as part of the maintenance programme.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_track_pads',
    shortLabel: 'Track pads — adequate condition, no missing or damaged pads',
    text: 'Are all track pads/shoes in adequate condition with no missing, cracked or excessively worn pads?',
    surveyGroup: 'Undercarriage & Tracks',
    allowNA: false,
    treatment: {
      name: 'Track Pads Condition',
      hazards: ['ROLLOVER', 'OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'MEDIUM', value: 14 },
      residualRating: { label: 'MEDIUM', value: 10 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Track pads must remain in adequate condition with no missing, cracked or excessively worn pads at all times. Missing or severely damaged pads must be replaced before operation on sealed surfaces.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_undercarriage_general',
    shortLabel: 'Undercarriage rollers, sprockets and idlers — free from major damage',
    text: 'Are the undercarriage rollers, carrier rollers, drive sprockets and front idlers free from major damage, cracks and excessive wear?',
    surveyGroup: 'Undercarriage & Tracks',
    allowNA: false,
    treatment: {
      name: 'Undercarriage Condition',
      hazards: ['OPERATIONAL MALFUNCTION', 'ROLLOVER'],
      prelimRating: { label: 'HIGH', value: 21 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Undercarriage components (rollers, sprockets, idlers) must remain free from major damage, cracks and excessive wear. Regular undercarriage inspections and measurements must be undertaken and documented as part of the maintenance programme.',
      references: 'AS/NZS4024.1201',
    },
  },
  {
    id: 'pt_q_vehicle_reversing_label',
    shortLabel: '"Vehicle Frequently Reversing" hazard warning label — rear of plant',
    text: 'Does this item of plant have a clear hazard warning label fitted to the rear re: Vehicle Frequently Reversing?',
    surveyGroup: 'Undercarriage & Tracks',
    allowNA: false,
    treatment: {
      name: 'Vehicle Frequently Reversing',
      hazards: ['CRUSHING', 'STRIKING', 'COLLISION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'OPERATION',
      treatmentText:
        'The rear of this item of plant has a hazard warning label re: vehicle frequently reversing. It must be present and kept serviceable and verified by the operator/owner at all times.',
      references: 'ISO20474-',
    },
  },

  // ─── PLANT CONDITION ─────────────────────────────────────────────────────
  {
    id: 'pt_q_free_from_leaks',
    shortLabel: 'Free from major leaks (engine, transmission, hydraulics, etc.)',
    text: 'Is this item of plant free from any major leaks? (this includes engine, transmission, cooling system, air, fuel, drive line and hydraulics)',
    surveyGroup: 'Plant Condition',
    allowNA: false,
    treatment: {
      name: 'Major Fluid Leaks',
      hazards: ['OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'LOW', value: 2 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'This item of plant must remain free from leaks at all times whilst in operation (this includes engine, transmission, cooling system, air, fuel, drive line and hydraulics). Development of a major leak will require this item of plant to be stood-down until repaired. Minor leaks detected must be repaired within 1-14 days.',
      references: 'ISO31000',
    },
  },
  {
    id: 'pt_q_original_condition',
    shortLabel: 'Plant in original condition — no modifications or upgrades',
    text: 'Is this item of plant in original condition, ie free from any form of modification or upgrade? (If you answer NO, please document location, type of modification and date in the assessor comments)',
    surveyGroup: 'Plant Condition',
    allowNA: false,
    treatment: {
      name: 'Plant Modification',
      hazards: ['OPERATIONAL MALFUNCTION'],
      prelimRating: { label: 'HIGH', value: 22 },
      residualRating: { label: 'LOW', value: 2 },
      operationCategory: 'DESIGN COMPLIANCE',
      treatmentText:
        'The plant is in original condition.',
      references: 'ISO31000',
    },
  },
  {
    id: 'pt_q_free_structural_damage',
    shortLabel: 'Free from structural damage (cracks, bends, damage to structural components)',
    text: 'Is this item of plant free from any structural damage? E.g. cracks in frames/chassis (current or repaired), bends or damage to structural components, etc.',
    surveyGroup: 'Plant Condition',
    allowNA: false,
    treatment: {
      name: 'Structural Integrity',
      hazards: ['CURRENT OR PREVIOUS STRUCTURAL DAMAGE'],
      prelimRating: { label: 'CRITICAL', value: 25 },
      residualRating: { label: 'MEDIUM', value: 15 },
      operationCategory: 'MAINTENANCE',
      treatmentText:
        'Regular checks for structural damage must be undertaken. Look for cracks in frames/chassis (current or repaired), bends or damage to structural components, etc.',
      references: 'ISO31000',
    },
  },
];
