'use client';

import { useEffect, useState } from 'react';
import SampleReportModal from '@/components/marketing/SampleReportModal';

const DAY_DOCKET_PDF_PATH = '/logbook/day%20docket.pdf';
const DAY_DOCKET_IFRAME_SRC = `${DAY_DOCKET_PDF_PATH}#toolbar=1&view=FitH`;

function useIsMobile() {
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia('(max-width: 768px)');
    const check = () => setIsMobile(mq.matches);
    check();
    mq.addEventListener('change', check);
    return () => mq.removeEventListener('change', check);
  }, []);
  return isMobile;
}

export default function DayDocketPreviewCard() {
  const [pdfModalOpen, setPdfModalOpen] = useState(false);
  const isMobile = useIsMobile();

  return (
    <div className="space-y-8">
      <div className="rounded-2xl border border-gray-200 bg-white p-6 sm:p-8 shadow-sm">
        <div className="border-b border-gray-100 pb-4 mb-5">
          <h4 className="text-lg font-semibold text-gray-900 tracking-tight">Day Docket</h4>
          <p className="mt-1 text-sm text-gray-600">Tuesday, Mar 24, 2026</p>
        </div>

        <p className="text-sm text-gray-800 leading-relaxed mb-6">
          <span className="font-medium text-gray-900">Total Hours:</span> 9 hrs 30 min
          <span className="mx-2 text-gray-300" aria-hidden>
            |
          </span>
          <span className="font-medium text-gray-900">Regular:</span> 8 hrs
          <span className="mx-2 text-gray-300" aria-hidden>
            |
          </span>
          <span className="font-medium text-gray-900">Overtime:</span> 1 hr 30 min
        </p>

        <dl className="space-y-3 text-sm">
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-gray-400">Machine</dt>
            <dd className="mt-0.5 font-medium text-gray-900">GRD-019</dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-gray-400">Employee</dt>
            <dd className="mt-0.5 font-medium text-gray-900">darcy — CivDocs Demo Pty Ltd</dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-gray-400">Job</dt>
            <dd className="mt-0.5 font-medium text-gray-900">Airport Carpark Upgrade</dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-gray-400">Attachments</dt>
            <dd className="mt-0.5 font-medium text-gray-900">UTS Full Day</dd>
          </div>
          <div>
            <dt className="text-xs font-medium uppercase tracking-wide text-gray-400">Hours</dt>
            <dd className="mt-0.5 font-medium text-gray-900">Start 07:00 → End 17:00, Break 30 min</dd>
          </div>
        </dl>

        <div className="mt-6 flex flex-wrap items-center gap-3">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-[#F5B041]/60 bg-gradient-to-r from-[#FF8C32]/10 to-[#F5B041]/10 px-3 py-1 text-xs font-semibold text-[#1E1E1E]">
            <span className="text-[#FF8C32]" aria-hidden>
              ✓
            </span>
            Supervisor Sign-Off — signed
          </span>
        </div>

        <p className="mt-6 border-t border-gray-100 pt-4 text-center text-xs text-gray-400">Generated by CivDocs</p>
      </div>

      <div>
        <div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <h4 className="text-base font-semibold text-gray-900">Sample Day Docket (PDF)</h4>
          <div className="flex flex-wrap items-center gap-3">
            <a
              href={DAY_DOCKET_PDF_PATH}
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm font-semibold text-[#FF8C32] hover:text-[#E67E22] transition-colors"
            >
              Open in new tab
            </a>
            <button
              type="button"
              onClick={() => setPdfModalOpen(true)}
              className="inline-flex items-center justify-center rounded-full border-2 border-gray-300 bg-white px-5 py-2 text-sm font-semibold text-gray-900 hover:border-[#FF8C32] hover:text-[#FF8C32] transition-all"
            >
              Full screen
            </button>
          </div>
        </div>

        {isMobile ? (
          <div className="rounded-xl border border-gray-200 bg-gray-50 px-6 py-10 text-center">
            <p className="text-gray-600 leading-relaxed">
              Mobile browsers can&apos;t scroll multi-page PDFs inline. Use the button below to open the sample Day
              Docket, or full screen for a larger view.
            </p>
            <a
              href={DAY_DOCKET_PDF_PATH}
              target="_blank"
              rel="noopener noreferrer"
              className="mt-6 inline-flex items-center justify-center rounded-full bg-gradient-to-r from-[#FF8C32] to-[#F5B041] px-10 py-4 text-lg font-semibold text-white shadow-md hover:shadow-lg"
            >
              Open PDF
            </a>
          </div>
        ) : (
          <iframe
            src={DAY_DOCKET_IFRAME_SRC}
            title="Sample Day Docket PDF"
            className="w-full min-h-[400px] rounded-xl border border-gray-200 bg-white shadow-sm"
            style={{ height: 'min(70vh, 640px)' }}
          />
        )}
      </div>

      <SampleReportModal
        isOpen={pdfModalOpen}
        onClose={() => setPdfModalOpen(false)}
        title="Sample Day Docket"
        description="Example Day Docket PDF generated by CivDocs — same document recipients get by email after sign-off."
        pdfPath={DAY_DOCKET_PDF_PATH}
        iframeTitle="Sample Day Docket PDF"
      />
    </div>
  );
}
