'use client';

import { useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface SampleReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const SAMPLE_PDF_URL = '/riskassesement/risk-assessment.pdf';

export default function SampleReportModal({ isOpen, onClose }: SampleReportModalProps) {
  useEffect(() => {
    if (!isOpen) return;
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', handleEscape);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = '';
    };
  }, [isOpen, onClose]);

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Dark overlay */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm"
            onClick={onClose}
            aria-hidden="true"
          />
          {/* Modal - nearly full screen on mobile */}
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.96 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-2 sm:inset-6 md:inset-8 z-[101] flex items-center justify-center pointer-events-none"
            role="dialog"
            aria-modal="true"
            aria-labelledby="sample-report-title"
          >
            <div
              className="pointer-events-auto w-full max-w-[900px] max-h-[95vh] sm:max-h-[90vh] flex flex-col bg-white rounded-2xl shadow-2xl overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Header with close button */}
              <div className="shrink-0 flex items-start justify-between gap-4 px-6 py-5 border-b border-gray-200 bg-white">
                <div>
                  <h2 id="sample-report-title" className="text-xl font-semibold text-gray-900">
                    Example Machine Risk Assessment Report
                  </h2>
                  <p className="mt-1 text-sm text-gray-500">
                    This is an example of the report generated by the CivDocs risk assessment generator.
                  </p>
                </div>
                <button
                  type="button"
                  onClick={onClose}
                  className="shrink-0 p-2 rounded-full text-gray-500 hover:text-gray-700 hover:bg-gray-100 transition-colors"
                  aria-label="Close modal"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
              {/* Scrollable content */}
              <div className="flex-1 min-h-0 overflow-y-auto overflow-x-hidden p-4 sm:p-6 pt-2 sm:pt-4">
                <iframe
                  src={SAMPLE_PDF_URL}
                  title="Example Machine Risk Assessment Report"
                  className="w-full h-[75vh] sm:h-[80vh] min-h-[400px] sm:min-h-[500px] rounded-lg border border-gray-200 bg-gray-50"
                />
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
