'use client';

import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface SampleReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  /** Modal heading */
  title?: string;
  /** Subtitle under the heading */
  description?: string;
  /** Path to a static PDF under `public/` (no hash; `#toolbar=1&view=FitH` is added for desktop iframe). */
  pdfPath?: string;
  /** `iframe` title / accessible name */
  iframeTitle?: string;
}

const DEFAULT_TITLE = 'Example Machine Risk Assessment Report';
const DEFAULT_DESCRIPTION =
  'This is an example of the report generated by the CivDocs risk assessment generator.';
const DEFAULT_PDF_PATH = '/riskassesement/risk-assessment.pdf';

function useIsMobile() {
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    const mq = window.matchMedia('(max-width: 768px)');
    const check = () => setIsMobile(mq.matches);
    check();
    mq.addEventListener('change', check);
    return () => mq.removeEventListener('change', check);
  }, []);
  return isMobile;
}

export default function SampleReportModal({
  isOpen,
  onClose,
  title = DEFAULT_TITLE,
  description = DEFAULT_DESCRIPTION,
  pdfPath = DEFAULT_PDF_PATH,
  iframeTitle = DEFAULT_TITLE,
}: SampleReportModalProps) {
  const isMobile = useIsMobile();
  const pdfPathForLink = pdfPath.split('#')[0];
  const iframeSrc = `${pdfPathForLink}#toolbar=1&view=FitH`;

  useEffect(() => {
    if (!isOpen) return;
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', handleEscape);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = '';
    };
  }, [isOpen, onClose]);

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Dark overlay */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm"
            onClick={onClose}
            aria-hidden="true"
          />
          {/* Modal - nearly full screen on mobile */}
          <motion.div
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.96 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-2 sm:inset-6 md:inset-8 z-[101] flex items-center justify-center pointer-events-none"
            role="dialog"
            aria-modal="true"
            aria-labelledby="sample-pdf-modal-title"
          >
            <div
              className="pointer-events-auto w-full max-w-[900px] max-h-[95vh] sm:max-h-[90vh] flex flex-col bg-white rounded-2xl shadow-2xl overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Header with close button */}
              <div className="shrink-0 flex items-start justify-between gap-4 px-6 py-5 border-b border-gray-200 bg-white">
                <div>
                  <h2 id="sample-pdf-modal-title" className="text-xl font-semibold text-gray-900">
                    {title}
                  </h2>
                  <p className="mt-1 text-sm text-gray-500">{description}</p>
                </div>
                <button
                  type="button"
                  onClick={onClose}
                  className="shrink-0 p-2 rounded-full text-gray-500 hover:text-gray-700 hover:bg-gray-100 transition-colors"
                  aria-label="Close modal"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
              {/* Scrollable content */}
              <div className="flex-1 min-h-0 overflow-y-auto overflow-x-hidden p-4 sm:p-6 pt-2 sm:pt-4">
                {isMobile ? (
                  <div className="flex min-h-[280px] flex-col items-center justify-center gap-6 px-4 py-8 text-center">
                    <p className="text-gray-600 text-sm sm:text-base">
                      Mobile browsers can&apos;t scroll multi-page PDFs reliably in this view. Open the PDF in a new tab to
                      view all pages.
                    </p>
                    <a
                      href={pdfPathForLink}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center justify-center rounded-full bg-gradient-to-r from-[#FF8C32] to-[#F5B041] px-10 py-4 text-lg font-semibold text-white shadow-md hover:shadow-lg"
                    >
                      Open PDF
                    </a>
                  </div>
                ) : (
                  <iframe
                    src={iframeSrc}
                    title={iframeTitle}
                    className="w-full h-[75vh] sm:h-[80vh] min-h-[400px] sm:min-h-[500px] rounded-xl border border-gray-200 bg-white shadow-sm"
                  />
                )}
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
