'use client';

import Footer from '@/components/Footer';
import Header from '@/components/Header';

export default function OrgSignupAgreementPage() {
  return (
    <div className="min-h-screen bg-white font-sans antialiased">
      <Header />
      <div className="pt-20">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-b from-white to-[#FFF5ED] pt-4 pb-16 sm:pt-12 sm:pb-20">
        <div className="max-w-4xl mx-auto px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-semibold text-[#1E1E1E] leading-tight tracking-tight mb-6">
              Organization Signup Agreement
            </h1>
            <p className="text-lg text-gray-600 leading-relaxed">
              Last Updated: 19 December 2024
            </p>
          </div>
        </div>
      </section>

      {/* Agreement Content */}
      <section className="py-16 sm:py-20 bg-white">
        <div className="max-w-4xl mx-auto px-6 lg:px-8">
          <div className="prose prose-lg max-w-none">
            {/* Introduction */}
            <div className="mb-12">
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  By creating an organization account on CivDocs, you acknowledge and agree to the following terms specific to organizational use of the Service. This agreement supplements the general Terms & Conditions and Privacy Policy.
                </p>
              </div>
            </div>

            {/* Section 1 */}
            <div className="mb-12 bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">1. NATURE OF CIVDOCS — PRODUCTIVITY TOOL ONLY</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  <strong>CivDocs is a productivity and information management tool only.</strong>
                </p>
                <p>
                  CivDocs is designed to help your organization record, organize, and display information entered by your users. It is not designed to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>verify or validate the accuracy of information entered</li>
                  <li>ensure compliance with workplace health and safety (WHS) laws</li>
                  <li>ensure compliance with payroll, tax, or legal obligations</li>
                  <li>act as a system of record for regulatory or statutory purposes</li>
                  <li>provide professional advice on safety, financial, legal, or compliance matters</li>
                </ul>
              </div>
            </div>

            {/* Section 2 */}
            <div className="mb-12 bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">2. ORGANIZATION RESPONSIBILITIES</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  As the organization administrator creating this account, you acknowledge and agree that:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li><strong>You are solely responsible</strong> for all operational, safety, financial, and legal decisions made by your organization</li>
                  <li><strong>You are responsible</strong> for ensuring all information entered into CivDocs by your users is accurate, complete, and compliant with applicable laws</li>
                  <li><strong>You are responsible</strong> for maintaining appropriate internal controls, review processes, and verification procedures</li>
                  <li><strong>You are responsible</strong> for workplace health and safety (WHS) compliance, regardless of any records maintained in CivDocs</li>
                  <li><strong>You are responsible</strong> for payroll, tax, and legal compliance, regardless of any calculations or reports generated by CivDocs</li>
                  <li><strong>You are responsible</strong> for maintaining independent records where required by law or regulation</li>
                </ul>
              </div>
            </div>

            {/* Section 3 */}
            <div className="mb-12 bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">3. NO VERIFICATION OR VALIDATION</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  CivDocs does not verify, validate, or certify:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>the accuracy of timesheet entries, pre-start inspections, or logbook records</li>
                  <li>compliance with WHS laws, regulations, or industry standards</li>
                  <li>the correctness of payroll calculations, tax obligations, or award rates</li>
                  <li>the legality or appropriateness of any operational decisions</li>
                  <li>the fitness for operation of any plant, equipment, or machinery</li>
                  <li>the qualifications, licenses, or certifications of users</li>
                </ul>
                <p>
                  All outputs generated by CivDocs (including reports, invoices, timesheets, analytics, AI outputs, and documents) are provided for informational purposes only and must be independently verified before use.
                </p>
              </div>
            </div>

            {/* Section 4 */}
            <div className="mb-12 bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">4. WORKPLACE HEALTH AND SAFETY</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  You acknowledge that:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>CivDocs does not enforce safety procedures or prevent unsafe operations</li>
                  <li>Pre-start checklists, fault logs, and safety reports in CivDocs are records only, based entirely on user input</li>
                  <li>CivDocs does not replace WHS systems, inspections, or controls</li>
                  <li>CivDocs does not guarantee the safety or suitability of any plant, equipment, or activity</li>
                  <li>Your organization remains solely responsible for workplace safety and WHS compliance</li>
                  <li>CivDocs is not liable for any WHS incidents, compliance failures, or regulatory breaches</li>
                </ul>
              </div>
            </div>

            {/* Section 5 */}
            <div className="mb-12 bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">5. FINANCIAL AND LEGAL COMPLIANCE</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  You acknowledge that:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Invoices and financial reports generated by CivDocs are user-generated documents and are not certified or legally validated</li>
                  <li>CivDocs does not provide accounting, payroll, tax, or award-rate calculations beyond basic arithmetic</li>
                  <li>All financial calculations must be reviewed and verified by qualified professionals before use</li>
                  <li>Your organization is responsible for ensuring compliance with all payroll, tax, and legal obligations</li>
                  <li>CivDocs is not liable for any financial, tax, or legal consequences arising from use of the Service</li>
                </ul>
              </div>
            </div>

            {/* Section 6 */}
            <div className="mb-12 bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">6. USER MANAGEMENT</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  As an organization administrator, you are responsible for:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>managing user access and permissions within your organization</li>
                  <li>ensuring users within your organization comply with CivDocs Terms & Conditions</li>
                  <li>maintaining the security of your organization account</li>
                  <li>ensuring all users are authorized to access the information they can view</li>
                  <li>removing access for users who are no longer authorized</li>
                </ul>
              </div>
            </div>

            {/* Section 7 */}
            <div className="mb-12 bg-amber-50 border-l-4 border-amber-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">7. DATA ACCURACY AND RELIANCE</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  You acknowledge that:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>All data in CivDocs is entered by your users and is not verified by CivDocs</li>
                  <li>CivDocs may contain incomplete, inaccurate, or outdated information</li>
                  <li>You must not rely on CivDocs as a substitute for professional judgment</li>
                  <li>All decisions made using information from CivDocs are made at your own risk</li>
                  <li>You are solely responsible for verifying all outputs before relying on them for any purpose</li>
                </ul>
              </div>
            </div>

            {/* Section 8 */}
            <div className="mb-12 bg-red-50 border-l-4 border-red-500 p-6 rounded-r-lg">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">8. LIMITATION OF LIABILITY</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p className="font-semibold uppercase">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, CIVDOCS SHALL NOT BE LIABLE FOR:
                </p>
                <ul className="list-disc pl-6 space-y-2 font-semibold uppercase">
                  <li>DECISIONS MADE BASED ON INFORMATION FROM THE SERVICE</li>
                  <li>INACCURACIES IN REPORTS, INVOICES, PRE-STARTS, TIMESHEETS, OR AI OUTPUTS</li>
                  <li>WHS INCIDENTS, COMPLIANCE FAILURES, OR REGULATORY BREACHES</li>
                  <li>PAYROLL, TAX, OR LEGAL NON-COMPLIANCE</li>
                  <li>INTERNAL MISUSE, FRAUD, OR MISCONDUCT BY USERS WITHIN YOUR ORGANIZATION</li>
                  <li>LOSS OF DATA, PROFITS, CONTRACTS, OR BUSINESS OPPORTUNITIES</li>
                </ul>
                <p>
                  To the maximum extent permitted by law, CivDocs' total liability is limited to the fees paid by your organization in the 12 months preceding the claim.
                </p>
              </div>
            </div>

            {/* Section 9 */}
            <div className="mb-12">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-4">9. ACKNOWLEDGMENT</h2>
              <div className="text-gray-700 leading-relaxed space-y-4">
                <p>
                  By creating an organization account on CivDocs, you acknowledge that:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You have read and understood this Organization Signup Agreement</li>
                  <li>You have read and understood the Terms & Conditions and Privacy Policy</li>
                  <li>You understand that CivDocs is a productivity tool only and does not provide professional advice or verification services</li>
                  <li>You accept full responsibility for all operational, safety, financial, and legal decisions made by your organization</li>
                  <li>You will maintain appropriate internal controls and verification procedures</li>
                  <li>You will not rely on CivDocs as a substitute for professional judgment</li>
                </ul>
              </div>
            </div>

            {/* Contact Section */}
            <div className="mb-12 mt-16 bg-gray-50 rounded-xl p-8">
              <h2 className="text-2xl sm:text-3xl font-semibold text-[#1E1E1E] mb-6">Contact Information</h2>
              <div className="text-gray-700 leading-relaxed space-y-3">
                <p>
                  If you have questions about this agreement, please contact us at:
                </p>
                <p className="text-lg">
                  📧 <a href="mailto:support@civdocs.com.au" className="text-[#FF8C32] hover:underline font-medium">support@civdocs.com.au</a>
                </p>
                <p className="font-medium">
                  CivDocs Pty Ltd<br />
                  ABN 16 691 993 049
                </p>
              </div>
            </div>

            <div className="border-t-2 border-gray-200 pt-8 mt-12">
              <p className="text-center text-lg font-semibold text-gray-900">
                By creating an organization account on CivDocs, you acknowledge that you have read, understood, and agree to be bound by this Organization Signup Agreement.
              </p>
            </div>
          </div>
        </div>
      </section>
      </div>

      {/* Footer */}
      <Footer />
    </div>
  );
}




