import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';

// ---------------------------------------------------------------------------
// Redfearn series: MGA (GDA94 / GDA2020 both use GRS80 ellipsoid)
// ---------------------------------------------------------------------------
function mgaToLatLon(easting: number, northing: number, zone: number): { lat: number; lon: number } {
  const a = 6378137.0;
  const f = 1 / 298.257222101;
  const e2 = 2 * f - f * f;
  const k0 = 0.9996;
  const E0 = 500000.0;
  const N0 = 10000000.0;
  const lon0 = ((zone * 6) - 183) * (Math.PI / 180);

  const x = easting - E0;
  const y = northing - N0;

  const e1 = (1 - Math.sqrt(1 - e2)) / (1 + Math.sqrt(1 - e2));
  const mu =
    y /
    (k0 * a * (1 - e2 / 4 - (3 * e2 ** 2) / 64 - (5 * e2 ** 3) / 256));

  const phi1 =
    mu +
    ((3 * e1) / 2 - (27 * e1 ** 3) / 32) * Math.sin(2 * mu) +
    ((21 * e1 ** 2) / 16 - (55 * e1 ** 4) / 32) * Math.sin(4 * mu) +
    ((151 * e1 ** 3) / 96) * Math.sin(6 * mu) +
    ((1097 * e1 ** 4) / 512) * Math.sin(8 * mu);

  const N1 = a / Math.sqrt(1 - e2 * Math.sin(phi1) ** 2);
  const T1 = Math.tan(phi1) ** 2;
  const C1 = (e2 / (1 - e2)) * Math.cos(phi1) ** 2;
  const R1 = (a * (1 - e2)) / Math.pow(1 - e2 * Math.sin(phi1) ** 2, 1.5);
  const D = x / (N1 * k0);

  const lat =
    phi1 -
    ((N1 * Math.tan(phi1)) / R1) *
      (D ** 2 / 2 -
        ((5 + 3 * T1 + 10 * C1 - 4 * C1 ** 2 - 9 * (e2 / (1 - e2))) *
          D ** 4) /
          24 +
        ((61 +
          90 * T1 +
          298 * C1 +
          45 * T1 ** 2 -
          252 * (e2 / (1 - e2)) -
          3 * C1 ** 2) *
          D ** 6) /
          720);

  const lon =
    lon0 +
    (D -
      ((1 + 2 * T1 + C1) * D ** 3) / 6 +
      ((5 - 2 * C1 + 28 * T1 - 3 * C1 ** 2 + 8 * (e2 / (1 - e2)) + 24 * T1 ** 2) *
        D ** 5) /
        120) /
      Math.cos(phi1);

  return { lat: lat * (180 / Math.PI), lon: lon * (180 / Math.PI) };
}

// ---------------------------------------------------------------------------
// CSV parser
// ---------------------------------------------------------------------------
interface Point {
  name: string;
  easting: number;
  northing: number;
  elevation: number;
  lat: number;
  lon: number;
}

function parseCsv(text: string, zone: number): Point[] {
  const points: Point[] = [];
  const lines = text.split(/\r?\n/);

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;

    const cols = line.split(',').map((c) => c.trim());
    if (cols.length < 4) continue;

    // Skip rows where the first field is a number (row-number column)
    const firstIsNum = !isNaN(Number(cols[0])) && cols[0] !== '';
    if (firstIsNum) continue;

    const [name, eastingStr, northingStr, elevationStr] = cols;
    const easting = parseFloat(eastingStr);
    const northing = parseFloat(northingStr);
    const elevation = parseFloat(elevationStr);

    if (!name || isNaN(easting) || isNaN(northing)) continue;

    const { lat, lon } = mgaToLatLon(easting, northing, zone);
    points.push({ name, easting, northing, elevation: isNaN(elevation) ? 0 : elevation, lat, lon });
  }

  return points;
}

// ---------------------------------------------------------------------------
// KML builder
// ---------------------------------------------------------------------------
function buildKml(points: Point[], datum: string, zone: number, filename: string): string {
  const datumLabel = datum === 'GDA2020' ? 'GDA2020 / MGA' : 'GDA94 / MGA';
  const placemarks = points
    .map(
      (p) => `  <Placemark>
    <name>${escapeXml(p.name)}</name>
    <description><![CDATA[
      <b>${escapeXml(p.name)}</b><br/>
      Easting: ${p.easting.toFixed(3)}<br/>
      Northing: ${p.northing.toFixed(3)}<br/>
      Elevation: ${p.elevation.toFixed(3)} m<br/>
      Datum/Zone: ${datumLabel} Zone ${zone}
    ]]></description>
    <Style>
      <IconStyle>
        <color>ff0000ff</color>
        <scale>0.8</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/shapes/placemark_circle.png</href>
        </Icon>
      </IconStyle>
      <LabelStyle>
        <scale>0.9</scale>
      </LabelStyle>
    </Style>
    <Point>
      <altitudeMode>clampToGround</altitudeMode>
      <coordinates>${p.lon.toFixed(8)},${p.lat.toFixed(8)},${p.elevation.toFixed(3)}</coordinates>
    </Point>
  </Placemark>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(filename)}</name>
    <description>Converted from CSV — ${datumLabel} Zone ${zone} — Generated by CivDocs</description>
${placemarks}
  </Document>
</kml>`;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// ---------------------------------------------------------------------------
// Route handler
// ---------------------------------------------------------------------------
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { csv, datum, zone, filename } = body as {
      csv: string;
      datum: string;
      zone: number;
      filename?: string;
    };

    if (!csv || typeof csv !== 'string') {
      return NextResponse.json({ error: 'Missing csv field' }, { status: 400 });
    }
    if (!datum || !['GDA2020', 'GDA94'].includes(datum)) {
      return NextResponse.json({ error: 'Invalid datum. Use GDA2020 or GDA94.' }, { status: 400 });
    }
    const zoneNum = Number(zone);
    if (!zoneNum || zoneNum < 46 || zoneNum > 56) {
      return NextResponse.json({ error: 'Zone must be between 46 and 56.' }, { status: 400 });
    }

    const points = parseCsv(csv, zoneNum);
    if (points.length === 0) {
      return NextResponse.json({ error: 'No valid points found in CSV. Check format: Name, Easting, Northing, Elevation.' }, { status: 422 });
    }

    const kmlFilename = filename ? filename.replace(/\.csv$/i, '') : 'points';
    const kml = buildKml(points, datum, zoneNum, kmlFilename);

    return NextResponse.json({ kml, points, filename: `${kmlFilename}.kml` });
  } catch (err) {
    console.error('[csv-to-kml] Error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
