import type { Metadata } from 'next';
import ReportViewer from './_components/ReportViewer';

export const metadata: Metadata = {
  title: 'Machine Risk Assessment Report — CivDocs',
  description: 'View your machine risk assessment report generated by CivDocs.',
  robots: { index: false, follow: false },
};

export default async function ReportPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  return <ReportViewer token={token} />;
}
