import type { Metadata } from 'next';
import ReportViewer from './_components/ReportViewer';

export const metadata: Metadata = {
  title: 'Machine Risk Assessment Report — CivDocs',
  description: 'View your machine risk assessment report generated by CivDocs.',
  robots: { index: false, follow: false },
};

export default function ReportPage({ params }: { params: { token: string } }) {
  return <ReportViewer token={params.token} />;
}
